//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.Workpiece
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Заготовки НСИ"
	/// </summary>
	public partial class FilterWorkpieceTypes
	{
		
		internal FilterWorkpieceTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Заготовки НСИ"
		/// </summary>
		public FilterWorkpieceType WorkpieceReferenceObject
		{
			get
			{
				return Find(Keys.WorkpieceReferenceObject);
			}
		}
		
		protected override FilterWorkpieceType CreateClassObject(Guid classGuid)
		{
			return new FilterWorkpieceType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Заготовки НСИ"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Заготовки НСИ"
			/// </summary>
		   public static readonly Guid WorkpieceReferenceObject = new Guid("c1fe37d1-e3b7-4496-a6ec-ab6789d05f72");

		}
	}
}
