//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.Workpiece
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Заготовки НСИ"
	/// </summary>
	public partial class FilterWorkpieceReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Заготовки НСИ"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("61b11402-e519-4d51-8125-982a81bab44b");
		
		/// <summary>
		/// Инициализирует новый экземпляр WorkpieceReference для работы с объектами справочника "Заготовки НСИ"
		/// </summary>
		public FilterWorkpieceReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, FilterWorkpieceReference.ReferenceId)
		{
		}
		
		private FilterWorkpieceReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Заготовки НСИ"
		/// </summary>
		public new FilterWorkpieceTypes Classes
		{
			get
			{
				return ((FilterWorkpieceTypes)(base.Classes));
			}
		}
		
		protected override FilterWorkpieceReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			FilterWorkpieceType type = classObject as FilterWorkpieceType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsWorkpieceReferenceObject)
			{
				return new FilterWorkpieceReferenceObject(this);
			}
			return new FilterWorkpieceReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<FilterWorkpieceReference, FilterWorkpieceTypes>
		{
			
			internal Factory()
			{
			}
			
			public override FilterWorkpieceReference CreateReference(ParameterGroup masterGroup)
			{
				return new FilterWorkpieceReference(masterGroup);
			}
			
			public override FilterWorkpieceTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new FilterWorkpieceTypes(masterGroup);
			}
		}
	}
}
