//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.FilterMaterial
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Материалы НСИ"
	/// </summary>
	public partial class FilterMaterialReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Материалы НСИ"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("aaae6fb9-eff5-4200-9ee5-8724de037f55");
		
		/// <summary>
		/// Инициализирует новый экземпляр FilterMaterialReference для работы с объектами справочника "Материалы НСИ"
		/// </summary>
		public FilterMaterialReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, FilterMaterialReference.ReferenceId)
		{
		}
		
		private FilterMaterialReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Материалы НСИ"
		/// </summary>
		public new FilterMaterialTypes Classes
		{
			get
			{
				return ((FilterMaterialTypes)(base.Classes));
			}
		}
		
		protected override FilterMaterialReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			FilterMaterialType type = classObject as FilterMaterialType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsFilterMaterialReferenceObject)
			{
				return new FilterMaterialReferenceObject(this);
			}
			return new FilterMaterialReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<FilterMaterialReference, FilterMaterialTypes>
		{
			
			internal Factory()
			{
			}
			
			public override FilterMaterialReference CreateReference(ParameterGroup masterGroup)
			{
				return new FilterMaterialReference(masterGroup);
			}
			
			public override FilterMaterialTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new FilterMaterialTypes(masterGroup);
			}
		}
	}
}
