//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.FilterMaterial
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Материалы НСИ"
	/// </summary>
	public partial class FilterMaterialTypes
	{
		
		internal FilterMaterialTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Материалы НСИ"
		/// </summary>
		public FilterMaterialType FilterMaterialReferenceObject
		{
			get
			{
				return Find(Keys.FilterMaterialReferenceObject);
			}
		}
		
		protected override FilterMaterialType CreateClassObject(Guid classGuid)
		{
			return new FilterMaterialType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Материалы НСИ"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Материалы НСИ"
			/// </summary>
		   public static readonly Guid FilterMaterialReferenceObject = new Guid("2313347f-8d44-451b-95be-727c4535991e");

		}
	}
}
