//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.FilterMaterial
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Материалы НСИ"
	/// </summary>
	public partial class FilterMaterialType
	{
		
		internal FilterMaterialType(FilterMaterialTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Материалы НСИ"
		/// </summary>
		public new FilterMaterialTypes Classes
		{
			get
			{
				return ((FilterMaterialTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Материалы НСИ" или порождён от него
		/// </summary>
		public bool IsFilterMaterialReferenceObject
		{
			get
			{
				return IsInherit(FilterMaterialTypes.Keys.FilterMaterialReferenceObject);
			}
		}
	}
}
