//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.CategoryProduct
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Товарные категории изделий"
	/// </summary>
	public partial class CategoryProductTypes
	{
		
		internal CategoryProductTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Товарная категория изделия"
		/// </summary>
		public CategoryProductType CategoryProductReferenceObject
		{
			get
			{
				return Find(Keys.CategoryProductReferenceObject);
			}
		}
		
		protected override CategoryProductType CreateClassObject(Guid classGuid)
		{
			return new CategoryProductType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Товарные категории изделий"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Товарная категория изделия"
			/// </summary>
		   public static readonly Guid CategoryProductReferenceObject = new Guid("9ada7742-f7f3-4292-af1a-665cecc94aca");

		}
	}
}
