//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.CategoryProduct
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.References.Links;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model.Parameters;
	
	
	/// <summary>
	/// Представляет объект справочника "Товарные категории изделий"
	/// </summary>
	public partial class CategoryProductReferenceObject
	{
		
		internal CategoryProductReferenceObject(CategoryProductReference reference) : 
				base(reference)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объекта
		/// </summary>
		public new CategoryProductType Class
		{
			get
			{
				return ((CategoryProductType)(base.Class));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Наименование"
		/// </summary>
		public StringParameter Name
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Name]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "GUID(1C)"
		/// </summary>
		public GuidParameter GUID_1C
		{
			get
			{
				return ((GuidParameter)(this[FieldKeys.GUID_1C]));
			}
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) параметров справочника "Товарные категории изделий"
		/// </summary>
		public class FieldKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Наименование"
			/// </summary>
		   public static readonly Guid Name = new Guid("f2d2b5aa-5a79-495c-bf91-923df99e85de");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "GUID(1C)"
			/// </summary>
		   public static readonly Guid GUID_1C = new Guid("42095537-abd1-434b-b872-2a8f9d262d2d");

		}
	}
}
