//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.CategoryProduct
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Товарные категории изделий"
	/// </summary>
	public partial class CategoryProductReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Товарные категории изделий"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("a6c5353f-f68f-4a25-8057-d1b636bb4648");
		
		/// <summary>
		/// Инициализирует новый экземпляр CategoryProductReference для работы с объектами справочника "Товарные категории изделий"
		/// </summary>
		public CategoryProductReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, CategoryProductReference.ReferenceId)
		{
		}
		
		private CategoryProductReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Товарные категории изделий"
		/// </summary>
		public new CategoryProductTypes Classes
		{
			get
			{
				return ((CategoryProductTypes)(base.Classes));
			}
		}
		
		protected override CategoryProductReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			CategoryProductType type = classObject as CategoryProductType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsCategoryProductReferenceObject)
			{
				return new CategoryProductReferenceObject(this);
			}
			return new CategoryProductReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<CategoryProductReference, CategoryProductTypes>
		{
			
			internal Factory()
			{
			}
			
			public override CategoryProductReference CreateReference(ParameterGroup masterGroup)
			{
				return new CategoryProductReference(masterGroup);
			}
			
			public override CategoryProductTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new CategoryProductTypes(masterGroup);
			}
		}
	}
}
