//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.CategoryProduct
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Товарные категории изделий"
	/// </summary>
	public partial class CategoryProductType
	{
		
		internal CategoryProductType(CategoryProductTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Товарные категории изделий"
		/// </summary>
		public new CategoryProductTypes Classes
		{
			get
			{
				return ((CategoryProductTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Товарная категория изделия" или порождён от него
		/// </summary>
		public bool IsCategoryProductReferenceObject
		{
			get
			{
				return IsInherit(CategoryProductTypes.Keys.CategoryProductReferenceObject);
			}
		}
	}
}
