//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.StandartProduct
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Эталонные стандартные изделия"
	/// </summary>
	public partial class EtalonStandartProductType
	{
		
		internal EtalonStandartProductType(EtalonStandartProductTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Эталонные стандартные изделия"
		/// </summary>
		public new EtalonStandartProductTypes Classes
		{
			get
			{
				return ((EtalonStandartProductTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Эталонные стандартные изделия" или порождён от него
		/// </summary>
		public bool IsStandartProductReferenceObject
		{
			get
			{
				return IsInherit(EtalonStandartProductTypes.Keys.StandartProductReferenceObject);
			}
		}
	}
}
