//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.StandartProduct
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Эталонные стандартные изделия"
	/// </summary>
	public partial class EtalonStandartProductReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Эталонные стандартные изделия"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("ea68ae3c-e71d-4352-84c2-553cbd2c7f2f");
		
		/// <summary>
		/// Инициализирует новый экземпляр StandartProductReference для работы с объектами справочника "Эталонные стандартные изделия"
		/// </summary>
		public EtalonStandartProductReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, EtalonStandartProductReference.ReferenceId)
		{
		}
		
		private EtalonStandartProductReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Эталонные стандартные изделия"
		/// </summary>
		public new EtalonStandartProductTypes Classes
		{
			get
			{
				return ((EtalonStandartProductTypes)(base.Classes));
			}
		}
		
		protected override EtalonStandartProductReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			EtalonStandartProductType type = classObject as EtalonStandartProductType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsStandartProductReferenceObject)
			{
				return new EtalonStandartProductReferenceObject(this);
			}
			return new EtalonStandartProductReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<EtalonStandartProductReference, EtalonStandartProductTypes>
		{
			
			internal Factory()
			{
			}
			
			public override EtalonStandartProductReference CreateReference(ParameterGroup masterGroup)
			{
				return new EtalonStandartProductReference(masterGroup);
			}
			
			public override EtalonStandartProductTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new EtalonStandartProductTypes(masterGroup);
			}
		}
	}
}
