//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.StandartProduct
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Эталонные стандартные изделия"
	/// </summary>
	public partial class StandartProductReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Эталонные стандартные изделия"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("ea68ae3c-e71d-4352-84c2-553cbd2c7f2f");
		
		/// <summary>
		/// Инициализирует новый экземпляр StandartProductReference для работы с объектами справочника "Эталонные стандартные изделия"
		/// </summary>
		public StandartProductReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, StandartProductReference.ReferenceId)
		{
		}
		
		private StandartProductReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Эталонные стандартные изделия"
		/// </summary>
		public new StandartProductTypes Classes
		{
			get
			{
				return ((StandartProductTypes)(base.Classes));
			}
		}
		
		protected override StandartProductReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			StandartProductType type = classObject as StandartProductType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsStandartProductReferenceObject)
			{
				return new StandartProductReferenceObject(this);
			}
			return new StandartProductReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<StandartProductReference, StandartProductTypes>
		{
			
			internal Factory()
			{
			}
			
			public override StandartProductReference CreateReference(ParameterGroup masterGroup)
			{
				return new StandartProductReference(masterGroup);
			}
			
			public override StandartProductTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new StandartProductTypes(masterGroup);
			}
		}
	}
}
