//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.StandartProduct
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Эталонные стандартные изделия"
	/// </summary>
	public partial class StandartProductTypes
	{
		
		internal StandartProductTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Эталонные стандартные изделия"
		/// </summary>
		public StandartProductType StandartProductReferenceObject
		{
			get
			{
				return Find(Keys.StandartProductReferenceObject);
			}
		}
		
		protected override StandartProductType CreateClassObject(Guid classGuid)
		{
			return new StandartProductType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Эталонные стандартные изделия"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Эталонные стандартные изделия"
			/// </summary>
		   public static readonly Guid StandartProductReferenceObject = new Guid("aa42487b-e492-4408-9f25-50eaab0d12cd");

		}
	}
}
