//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.FilterOiginalMaket
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Оригинал-макеты НСИ"
	/// </summary>
	public partial class FilterOriginalMaketTypes
	{
		
		internal FilterOriginalMaketTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Оригинал-макеты НСИ"
		/// </summary>
		public FilterOriginalMaketType FilterOiginalMaketReferenceObject
		{
			get
			{
				return Find(Keys.FilterOiginalMaketReferenceObject);
			}
		}
		
		protected override FilterOriginalMaketType CreateClassObject(Guid classGuid)
		{
			return new FilterOriginalMaketType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Оригинал-макеты НСИ"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Оригинал-макеты НСИ"
			/// </summary>
		   public static readonly Guid FilterOiginalMaketReferenceObject = new Guid("5f04e4cf-75c5-4974-ab14-5c8d27bf3edd");

		}
	}
}
