//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.FilterOiginalMaket
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Оригинал-макеты НСИ"
	/// </summary>
	public partial class FilterOriginalMaketReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Оригинал-макеты НСИ"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("fb866bd5-d2c1-4015-87cb-c4f5f07bf1c4");
		
		/// <summary>
		/// Инициализирует новый экземпляр FilterOiginalMaketReference для работы с объектами справочника "Оригинал-макеты НСИ"
		/// </summary>
		public FilterOriginalMaketReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, FilterOriginalMaketReference.ReferenceId)
		{
		}
		
		private FilterOriginalMaketReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Оригинал-макеты НСИ"
		/// </summary>
		public new FilterOriginalMaketTypes Classes
		{
			get
			{
				return ((FilterOriginalMaketTypes)(base.Classes));
			}
		}
		
		protected override FilterOriginalMaketReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			FilterOriginalMaketType type = classObject as FilterOriginalMaketType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsFilterOiginalMaketReferenceObject)
			{
				return new FilterOriginalMaketReferenceObject(this);
			}
			return new FilterOriginalMaketReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<FilterOriginalMaketReference, FilterOriginalMaketTypes>
		{
			
			internal Factory()
			{
			}
			
			public override FilterOriginalMaketReference CreateReference(ParameterGroup masterGroup)
			{
				return new FilterOriginalMaketReference(masterGroup);
			}
			
			public override FilterOriginalMaketTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new FilterOriginalMaketTypes(masterGroup);
			}
		}
	}
}
