//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.FilterOiginalMaket
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.References.Links;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model.Parameters;
	
	
	/// <summary>
	/// Представляет объект справочника "Оригинал-макеты НСИ"
	/// </summary>
	public partial class FilterOriginalMaketReferenceObject
	{
		
		internal FilterOriginalMaketReferenceObject(FilterOriginalMaketReference reference) : 
				base(reference)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объекта
		/// </summary>
		public new FilterOriginalMaketType Class
		{
			get
			{
				return ((FilterOriginalMaketType)(base.Class));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Наименование"
		/// </summary>
		//public StringParameter Name
		//{
		//	get
		//	{
		//		return ((StringParameter)(this[FieldKeys.Name]));
		//	}
		//}
		
		/// <summary>
		/// Возвращает параметр "Классификация"
		/// </summary>
		public StringParameter Classification
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Classification]));
			}
		}
		
		/// <summary>
		/// Возвращает или задаёт связанный объект справочника "Номенклатура ERP" по связи "Входящая номенклатура"
		/// </summary>
		public ReferenceObject InputNomenclature
		{
			get
			{
				return GetObject(RelationKeys.InputNomenclature);
			}
			set
			{
				SetLinkedObject(RelationKeys.InputNomenclature, value);
			}
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) параметров справочника "Оригинал-макеты НСИ"
		/// </summary>
		public class FieldKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Наименование"
			/// </summary>
		   //public static readonly Guid Name = new Guid("38b05bb1-7f52-4f67-b64d-4e8c313d692f");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Классификация"
			/// </summary>
		   public static readonly Guid Classification = new Guid("d01348a2-4a55-43fe-8b9e-3287fea52f8f");

		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) связей и списков объектов справочника "Оригинал-макеты НСИ"
		/// </summary>
		public class RelationKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Входящая номенклатура"
			/// </summary>
		   public static readonly Guid InputNomenclature = new Guid("8318119c-d6ab-4e78-893b-d87c4f8671a5");

		}
	}
}
