//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.TypeReproductionERP
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Типы воспроизводства"
	/// </summary>
	public partial class TypeReproductionERPTypes
	{
		
		internal TypeReproductionERPTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Тип воспроизводства"
		/// </summary>
		public TypeReproductionERPType TypeReproductionERPReferenceObject
		{
			get
			{
				return Find(Keys.TypeReproductionERPReferenceObject);
			}
		}
		
		protected override TypeReproductionERPType CreateClassObject(Guid classGuid)
		{
			return new TypeReproductionERPType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Типы воспроизводства"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Тип воспроизводства"
			/// </summary>
		   public static readonly Guid TypeReproductionERPReferenceObject = new Guid("b5fbc12c-e11e-43dd-9ae2-f125f6bd0d48");

		}
	}
}
