//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.TypeReproductionERP
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.References.Links;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model.Parameters;
	
	
	/// <summary>
	/// Представляет объект справочника "Типы воспроизводства"
	/// </summary>
	public partial class TypeReproductionERPReferenceObject
	{
		
		internal TypeReproductionERPReferenceObject(TypeReproductionERPReference reference) : 
				base(reference)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объекта
		/// </summary>
		public new TypeReproductionERPType Class
		{
			get
			{
				return ((TypeReproductionERPType)(base.Class));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Наименование"
		/// </summary>
		public StringParameter Name
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Name]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "GUID(1C)"
		/// </summary>
		public GuidParameter GUID_1C
		{
			get
			{
				return ((GuidParameter)(this[FieldKeys.GUID_1C]));
			}
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) параметров справочника "Типы воспроизводства"
		/// </summary>
		public class FieldKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Наименование"
			/// </summary>
		   public static readonly Guid Name = new Guid("e7d18c2b-d0e2-44dc-8d4d-678567a5be1d");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "GUID(1C)"
			/// </summary>
		   public static readonly Guid GUID_1C = new Guid("8d494d89-4115-42d0-b74a-f14ad77eee39");

		}
	}
}
