//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.TypeReproductionERP
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Типы воспроизводства"
	/// </summary>
	public partial class TypeReproductionERPType
	{
		
		internal TypeReproductionERPType(TypeReproductionERPTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Типы воспроизводства"
		/// </summary>
		public new TypeReproductionERPTypes Classes
		{
			get
			{
				return ((TypeReproductionERPTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Тип воспроизводства" или порождён от него
		/// </summary>
		public bool IsTypeReproductionERPReferenceObject
		{
			get
			{
				return IsInherit(TypeReproductionERPTypes.Keys.TypeReproductionERPReferenceObject);
			}
		}
	}
}
