//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.TypeReproductionERP
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Типы воспроизводства"
	/// </summary>
	public partial class TypeReproductionERPReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Типы воспроизводства"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("207b8dde-6217-4048-b110-14feed14be57");
		
		/// <summary>
		/// Инициализирует новый экземпляр TypeReproductionERPReference для работы с объектами справочника "Типы воспроизводства"
		/// </summary>
		public TypeReproductionERPReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, TypeReproductionERPReference.ReferenceId)
		{
		}
		
		private TypeReproductionERPReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Типы воспроизводства"
		/// </summary>
		public new TypeReproductionERPTypes Classes
		{
			get
			{
				return ((TypeReproductionERPTypes)(base.Classes));
			}
		}
		
		protected override TypeReproductionERPReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			TypeReproductionERPType type = classObject as TypeReproductionERPType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsTypeReproductionERPReferenceObject)
			{
				return new TypeReproductionERPReferenceObject(this);
			}
			return new TypeReproductionERPReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<TypeReproductionERPReference, TypeReproductionERPTypes>
		{
			
			internal Factory()
			{
			}
			
			public override TypeReproductionERPReference CreateReference(ParameterGroup masterGroup)
			{
				return new TypeReproductionERPReference(masterGroup);
			}
			
			public override TypeReproductionERPTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new TypeReproductionERPTypes(masterGroup);
			}
		}
	}
}
