//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.UnitOfMeasurement
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Единицы измерения 1C"
	/// </summary>
	public partial class UnitOfMeasurementReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Единицы измерения 1C"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("72389221-8bee-456a-9e0e-1694ec5fe4ff");
		
		/// <summary>
		/// Инициализирует новый экземпляр UnitOfMeasurementReference для работы с объектами справочника "Единицы измерения 1C"
		/// </summary>
		public UnitOfMeasurementReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, UnitOfMeasurementReference.ReferenceId)
		{
		}
		
		private UnitOfMeasurementReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Единицы измерения 1C"
		/// </summary>
		public new UnitOfMeasurementTypes Classes
		{
			get
			{
				return ((UnitOfMeasurementTypes)(base.Classes));
			}
		}
		
		protected override UnitOfMeasurementReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			UnitOfMeasurementType type = classObject as UnitOfMeasurementType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsUnitOfMeasurementReferenceObject)
			{
				return new UnitOfMeasurementReferenceObject(this);
			}
			return new UnitOfMeasurementReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<UnitOfMeasurementReference, UnitOfMeasurementTypes>
		{
			
			internal Factory()
			{
			}
			
			public override UnitOfMeasurementReference CreateReference(ParameterGroup masterGroup)
			{
				return new UnitOfMeasurementReference(masterGroup);
			}
			
			public override UnitOfMeasurementTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new UnitOfMeasurementTypes(masterGroup);
			}
		}
	}
}
