//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.UnitOfMeasurement
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Единицы измерения 1C"
	/// </summary>
	public partial class UnitOfMeasurementTypes
	{
		
		internal UnitOfMeasurementTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Единицы измерения 1C"
		/// </summary>
		public UnitOfMeasurementType UnitOfMeasurementReferenceObject
		{
			get
			{
				return Find(Keys.UnitOfMeasurementReferenceObject);
			}
		}
		
		protected override UnitOfMeasurementType CreateClassObject(Guid classGuid)
		{
			return new UnitOfMeasurementType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Единицы измерения 1C"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Единицы измерения 1C"
			/// </summary>
		   public static readonly Guid UnitOfMeasurementReferenceObject = new Guid("561f068c-bcd1-42ff-b988-971eade64e24");

		}
	}
}
