//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.UnitOfMeasurement
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Единицы измерения 1C"
	/// </summary>
	public partial class UnitOfMeasurementType
	{
		
		internal UnitOfMeasurementType(UnitOfMeasurementTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Единицы измерения 1C"
		/// </summary>
		public new UnitOfMeasurementTypes Classes
		{
			get
			{
				return ((UnitOfMeasurementTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Единицы измерения 1C" или порождён от него
		/// </summary>
		public bool IsUnitOfMeasurementReferenceObject
		{
			get
			{
				return IsInherit(UnitOfMeasurementTypes.Keys.UnitOfMeasurementReferenceObject);
			}
		}
	}
}
