//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.UnitOfMeasurement
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.References.Links;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model.Parameters;
	
	
	/// <summary>
	/// Представляет объект справочника "Единицы измерения 1C"
	/// </summary>
	public partial class UnitOfMeasurementReferenceObject
	{
		
		internal UnitOfMeasurementReferenceObject(UnitOfMeasurementReference reference) : 
				base(reference)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объекта
		/// </summary>
		public new UnitOfMeasurementType Class
		{
			get
			{
				return ((UnitOfMeasurementType)(base.Class));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Наименование"
		/// </summary>
		public StringParameter Name
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Name]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "GUID(1C)"
		/// </summary>
		public GuidParameter GUID_1C
		{
			get
			{
				return ((GuidParameter)(this[FieldKeys.GUID_1C]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Наименование типа"
		/// </summary>
		public StringParameter Naimenovanie_tipa
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Naimenovanie_tipa]));
			}
		}
		
		/// <summary>
		/// Возвращает или задаёт связанный объект справочника "Единицы измерения" по связи "Связанная единица измерения"
		/// </summary>
		public ReferenceObject LinkUnitOfMeasurement
		{
			get
			{
				return GetObject(RelationKeys.LinkUnitOfMeasurement);
			}
			set
			{
				SetLinkedObject(RelationKeys.LinkUnitOfMeasurement, value);
			}
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) параметров справочника "Единицы измерения 1C"
		/// </summary>
		public class FieldKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Наименование"
			/// </summary>
		   public static readonly Guid Name = new Guid("5d3015ef-dae9-4ef0-b0e2-7d828563f42e");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "GUID(1C)"
			/// </summary>
		   public static readonly Guid GUID_1C = new Guid("b616afe2-4f07-4e52-96bc-64df8dc3f473");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Наименование типа"
			/// </summary>
		   public static readonly Guid Naimenovanie_tipa = new Guid("9416d622-629d-43f5-b621-ad9f6f1e7a20");

		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) связей и списков объектов справочника "Единицы измерения 1C"
		/// </summary>
		public class RelationKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Связанная единица измерения"
			/// </summary>
		   public static readonly Guid LinkUnitOfMeasurement = new Guid("1d011f8f-83b8-4611-8f8e-bb90f02ae195");

		}
	}
}
