//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.FilterDetaliAssembling
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Детали и сборки НСИ"
	/// </summary>
	public partial class FilterDetaliAssemblingTypes
	{
		
		internal FilterDetaliAssemblingTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Детали и сборки НСИ"
		/// </summary>
		public FilterDetaliAssemblingType FilterDetaliAssemblingReferenceObject
		{
			get
			{
				return Find(Keys.FilterDetaliAssemblingReferenceObject);
			}
		}
		
		protected override FilterDetaliAssemblingType CreateClassObject(Guid classGuid)
		{
			return new FilterDetaliAssemblingType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Детали и сборки НСИ"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Детали и сборки НСИ"
			/// </summary>
		   public static readonly Guid FilterDetaliAssemblingReferenceObject = new Guid("90f4de87-e8cd-471a-a895-9f10a1c92e7f");

		}
	}
}
