//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.FilterDetaliAssembling
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Детали и сборки НСИ"
	/// </summary>
	public partial class FilterDetaliAssemblingType
	{
		
		internal FilterDetaliAssemblingType(FilterDetaliAssemblingTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Детали и сборки НСИ"
		/// </summary>
		public new FilterDetaliAssemblingTypes Classes
		{
			get
			{
				return ((FilterDetaliAssemblingTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Детали и сборки НСИ" или порождён от него
		/// </summary>
		public bool IsFilterDetaliAssemblingReferenceObject
		{
			get
			{
				return IsInherit(FilterDetaliAssemblingTypes.Keys.FilterDetaliAssemblingReferenceObject);
			}
		}
	}
}
