//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.ApplicabiltyMaterials
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Применение материала"
	/// </summary>
	public partial class ApplicabiltyMaterialsTypes
	{
		
		internal ApplicabiltyMaterialsTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Применение материала"
		/// </summary>
		public ApplicabiltyMaterialsType ApplicabiltyMaterialsReferenceObject
		{
			get
			{
				return Find(Keys.ApplicabiltyMaterialsReferenceObject);
			}
		}
		
		protected override ApplicabiltyMaterialsType CreateClassObject(Guid classGuid)
		{
			return new ApplicabiltyMaterialsType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Применение материала"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Применение материала"
			/// </summary>
		   public static readonly Guid ApplicabiltyMaterialsReferenceObject = new Guid("9cea9829-70f1-46a8-8937-5b5c834754d3");

		}
	}
}
