//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.ApplicabiltyMaterials
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Применение материала"
	/// </summary>
	public partial class ApplicabiltyMaterialsType
	{
		
		internal ApplicabiltyMaterialsType(ApplicabiltyMaterialsTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Применение материала"
		/// </summary>
		public new ApplicabiltyMaterialsTypes Classes
		{
			get
			{
				return ((ApplicabiltyMaterialsTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Применение материала" или порождён от него
		/// </summary>
		public bool IsApplicabiltyMaterialsReferenceObject
		{
			get
			{
				return IsInherit(ApplicabiltyMaterialsTypes.Keys.ApplicabiltyMaterialsReferenceObject);
			}
		}
	}
}
