//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.EtalonOriginalMaket
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Эталонные оригинал-макеты"
	/// </summary>
	public partial class EtalonOriginalMaketType
	{
		
		internal EtalonOriginalMaketType(EtalonOriginalMaketTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Эталонные оригинал-макеты"
		/// </summary>
		public new EtalonOriginalMaketTypes Classes
		{
			get
			{
				return ((EtalonOriginalMaketTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Эталонные оригинал-макеты" или порождён от него
		/// </summary>
		public bool IsEtalonOriginalMaketReferenceObject
		{
			get
			{
				return IsInherit(EtalonOriginalMaketTypes.Keys.EtalonOriginalMaketReferenceObject);
			}
		}
	}
}
