//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.EtalonOriginalMaket
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Эталонные оригинал-макеты"
	/// </summary>
	public partial class EtalonOriginalMaketReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Эталонные оригинал-макеты"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("5c57a5a6-6614-43c7-b881-9b53ad982637");
		
		/// <summary>
		/// Инициализирует новый экземпляр EtalonOriginalMaketReference для работы с объектами справочника "Эталонные оригинал-макеты"
		/// </summary>
		public EtalonOriginalMaketReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, EtalonOriginalMaketReference.ReferenceId)
		{
		}
		
		private EtalonOriginalMaketReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Эталонные оригинал-макеты"
		/// </summary>
		public new EtalonOriginalMaketTypes Classes
		{
			get
			{
				return ((EtalonOriginalMaketTypes)(base.Classes));
			}
		}
		
		protected override EtalonOriginalMaketReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			EtalonOriginalMaketType type = classObject as EtalonOriginalMaketType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsEtalonOriginalMaketReferenceObject)
			{
				return new EtalonOriginalMaketReferenceObject(this);
			}
			return new EtalonOriginalMaketReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<EtalonOriginalMaketReference, EtalonOriginalMaketTypes>
		{
			
			internal Factory()
			{
			}
			
			public override EtalonOriginalMaketReference CreateReference(ParameterGroup masterGroup)
			{
				return new EtalonOriginalMaketReference(masterGroup);
			}
			
			public override EtalonOriginalMaketTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new EtalonOriginalMaketTypes(masterGroup);
			}
		}
	}
}
