//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.EtalonOriginalMaket
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.References.Links;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model.Parameters;
	
	
	/// <summary>
	/// Представляет объект справочника "Эталонные оригинал-макеты"
	/// </summary>
	public partial class EtalonOriginalMaketReferenceObject
	{
		
		internal EtalonOriginalMaketReferenceObject(EtalonOriginalMaketReference reference) : 
				base(reference)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объекта
		/// </summary>
		public new EtalonOriginalMaketType Class
		{
			get
			{
				return ((EtalonOriginalMaketType)(base.Class));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Наименование"
		/// </summary>
		public StringParameter Name
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Name]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Обозначение"
		/// </summary>
		public StringParameter Denotation
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Denotation]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Тип оригинал макета"
		/// </summary>
		public StringParameter TypeOriginalMaket
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.TypeOriginalMaket]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Нетиповая продукция"
		/// </summary>
		public BooleanParameter IsNotTypicalProduct
		{
			get
			{
				return ((BooleanParameter)(this[FieldKeys.IsNotTypicalProduct]));
			}
		}
		
		/// <summary>
		/// Возвращает или задаёт связанный объект справочника "Номенклатура ERP" по связи "Номенклатура ERP ОМ"
		/// </summary>
		public ReferenceObject Nomenclature
		{
			get
			{
				return GetObject(RelationKeys.Nomenclature);
			}
			set
			{
				SetLinkedObject(RelationKeys.Nomenclature, value);
			}
		}
		
		/// <summary>
		/// Возвращает связанные объекты справочника "Справочник эквивалентов MDM" по связи "Эквиваленты оригинал макета MDM"
		/// </summary>
		public ReferenceObjectCollection Equivalent
		{
			get
			{
				return Links.ToMany[RelationKeys.Equivalent].Objects;
			}
		}
		
		/// <summary>
		/// Подключает объект справочника "Справочник эквивалентов MDM" по связи "Эквиваленты оригинал макета MDM"
		/// </summary>
		/// <param name="newLinkedObject">
		/// Подключаемый объект
		/// </param>
		/// <returns>
		/// Подключённый объект
		/// </returns>
		public ReferenceObject AddEquivalent(ReferenceObject newLinkedObject)
		{
			return AddLinkedObject(RelationKeys.Equivalent, newLinkedObject);
		}
		
		/// <summary>
		/// Отключает объект справочника "Справочник эквивалентов MDM" по связи "Эквиваленты оригинал макета MDM"
		/// </summary>
		/// <param name="linkedObject">
		/// Связанный объект
		/// </param>
		/// <returns>
		/// true, если объект был отключен
		/// </returns>
		public Boolean RemoveEquivalent(ReferenceObject linkedObject)
		{
			return RemoveLinkedObject(RelationKeys.Equivalent, linkedObject);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) параметров справочника "Эталонные оригинал-макеты"
		/// </summary>
		public class FieldKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Наименование"
			/// </summary>
		   public static readonly Guid Name = new Guid("da10fb28-d2d0-477f-991f-0ad6483ecc27");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Обозначение"
			/// </summary>
		   public static readonly Guid Denotation = new Guid("84e44090-f2f1-4ff0-b22f-efba5fd8befe");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Тип оригинал макета"
			/// </summary>
		   public static readonly Guid TypeOriginalMaket = new Guid("333b0d40-5f1e-4757-a76b-3c3d25cc8b62");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Нетиповая продукция"
			/// </summary>
		   public static readonly Guid IsNotTypicalProduct = new Guid("3280b045-3ee0-45af-b5ae-f8d061ddd1b2");

		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) связей и списков объектов справочника "Эталонные оригинал-макеты"
		/// </summary>
		public class RelationKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Номенклатура ERP ОМ"
			/// </summary>
		   public static readonly Guid Nomenclature = new Guid("1531fa73-d8a6-4347-83c3-cc8ac233eaa5");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Эквиваленты оригинал макета MDM"
			/// </summary>
		   public static readonly Guid Equivalent = new Guid("40d65d56-d5e2-4d7c-a0b8-c27618d933b6");

		}
	}
}
