//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.EtalonOriginalMaket
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Эталонные оригинал-макеты"
	/// </summary>
	public partial class EtalonOriginalMaketTypes
	{
		
		internal EtalonOriginalMaketTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Эталонные оригинал-макеты"
		/// </summary>
		public EtalonOriginalMaketType EtalonOriginalMaketReferenceObject
		{
			get
			{
				return Find(Keys.EtalonOriginalMaketReferenceObject);
			}
		}
		
		protected override EtalonOriginalMaketType CreateClassObject(Guid classGuid)
		{
			return new EtalonOriginalMaketType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Эталонные оригинал-макеты"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Эталонные оригинал-макеты"
			/// </summary>
		   public static readonly Guid EtalonOriginalMaketReferenceObject = new Guid("a4313de1-3ed5-45cd-b379-43855258a67d");

		}
	}
}
