//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.EtalonProductOther
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Эталонные прочие изделия"
	/// </summary>
	public partial class EtalonProductOtherReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Эталонные прочие изделия"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("a27f4aee-6629-457b-8c72-02c9e1a66ed6");
		
		/// <summary>
		/// Инициализирует новый экземпляр EtalonProductOtherReference для работы с объектами справочника "Эталонные прочие изделия"
		/// </summary>
		public EtalonProductOtherReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, EtalonProductOtherReference.ReferenceId)
		{
		}
		
		private EtalonProductOtherReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Эталонные прочие изделия"
		/// </summary>
		public new EtalonProductOtherTypes Classes
		{
			get
			{
				return ((EtalonProductOtherTypes)(base.Classes));
			}
		}
		
		protected override EtalonProductOtherReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			EtalonProductOtherType type = classObject as EtalonProductOtherType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsEtalonProductOtherReferenceObject)
			{
				return new EtalonProductOtherReferenceObject(this);
			}
			return new EtalonProductOtherReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<EtalonProductOtherReference, EtalonProductOtherTypes>
		{
			
			internal Factory()
			{
			}
			
			public override EtalonProductOtherReference CreateReference(ParameterGroup masterGroup)
			{
				return new EtalonProductOtherReference(masterGroup);
			}
			
			public override EtalonProductOtherTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new EtalonProductOtherTypes(masterGroup);
			}
		}
	}
}
