//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.EtalonProductOther
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.References.Links;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model.Parameters;
	
	
	/// <summary>
	/// Представляет объект справочника "Эталонные прочие изделия"
	/// </summary>
	public partial class EtalonProductOtherReferenceObject
	{
		
		internal EtalonProductOtherReferenceObject(EtalonProductOtherReference reference) : 
				base(reference)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объекта
		/// </summary>
		public new EtalonProductOtherType Class
		{
			get
			{
				return ((EtalonProductOtherType)(base.Class));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Наименование"
		/// </summary>
		public StringParameter Name
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Name]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Обозначение"
		/// </summary>
		public StringParameter Denotation
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Denotation]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Покупное"
		/// </summary>
		public BooleanParameter IsBuying
		{
			get
			{
				return ((BooleanParameter)(this[FieldKeys.IsBuying]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Конечное изделие"
		/// </summary>
		public BooleanParameter IsFinalProduct
		{
			get
			{
				return ((BooleanParameter)(this[FieldKeys.IsFinalProduct]));
			}
		}
		
		/// <summary>
		/// Возвращает или задаёт связанный объект справочника "Номенклатура ERP" по связи "Номенклатура ERP ПИ"
		/// </summary>
		public ReferenceObject Nomenclature
		{
			get
			{
				return GetObject(RelationKeys.Nomenclature);
			}
			set
			{
				SetLinkedObject(RelationKeys.Nomenclature, value);
			}
		}
		
		/// <summary>
		/// Возвращает связанные объекты справочника "Справочник эквивалентов MDM" по связи "Эквиваленты прочих изделий MDM"
		/// </summary>
		public ReferenceObjectCollection Equivalent
		{
			get
			{
				return Links.ToMany[RelationKeys.Equivalent].Objects;
			}
		}
		
		/// <summary>
		/// Подключает объект справочника "Справочник эквивалентов MDM" по связи "Эквиваленты прочих изделий MDM"
		/// </summary>
		/// <param name="newLinkedObject">
		/// Подключаемый объект
		/// </param>
		/// <returns>
		/// Подключённый объект
		/// </returns>
		public ReferenceObject AddEquivalent(ReferenceObject newLinkedObject)
		{
			return AddLinkedObject(RelationKeys.Equivalent, newLinkedObject);
		}
		
		/// <summary>
		/// Отключает объект справочника "Справочник эквивалентов MDM" по связи "Эквиваленты прочих изделий MDM"
		/// </summary>
		/// <param name="linkedObject">
		/// Связанный объект
		/// </param>
		/// <returns>
		/// true, если объект был отключен
		/// </returns>
		public Boolean RemoveEquivalent(ReferenceObject linkedObject)
		{
			return RemoveLinkedObject(RelationKeys.Equivalent, linkedObject);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) параметров справочника "Эталонные прочие изделия"
		/// </summary>
		public class FieldKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Наименование"
			/// </summary>
		   public static readonly Guid Name = new Guid("0b022b20-9f2d-49aa-b131-ccd9b1f74dc2");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Обозначение"
			/// </summary>
		   public static readonly Guid Denotation = new Guid("6d850028-8662-4808-8a90-f3d3af6dc758");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Покупное"
			/// </summary>
		   public static readonly Guid IsBuying = new Guid("03263f28-ac17-483b-bf40-f86d5a1dec5a");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Конечное изделие"
			/// </summary>
		   public static readonly Guid IsFinalProduct = new Guid("458acec3-1b01-44ce-ac80-365312d601af");

		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) связей и списков объектов справочника "Эталонные прочие изделия"
		/// </summary>
		public class RelationKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Номенклатура ERP ПИ"
			/// </summary>
		   public static readonly Guid Nomenclature = new Guid("75c5ae89-176a-4adf-a7f9-0b3d49fb319a");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Эквиваленты прочих изделий MDM"
			/// </summary>
		   public static readonly Guid Equivalent = new Guid("7f1d2e69-2f6a-47f6-8437-c3e3e133fb4f");

		}
	}
}
