//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.EtalonElectronicCompoents
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Эталоны электронных компонентов"
	/// </summary>
	public partial class EtalonElectronicCompoentsType
	{
		
		internal EtalonElectronicCompoentsType(EtalonElectronicCompoentsTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Эталоны электронных компонентов"
		/// </summary>
		public new EtalonElectronicCompoentsTypes Classes
		{
			get
			{
				return ((EtalonElectronicCompoentsTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Эталоны электронных компонентов" или порождён от него
		/// </summary>
		public bool IsEtalonElectronicCompoentsReferenceObject
		{
			get
			{
				return IsInherit(EtalonElectronicCompoentsTypes.Keys.EtalonElectronicCompoentsReferenceObject);
			}
		}
	}
}
