//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.EtalonElectronicCompoents
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Эталоны электронных компонентов"
	/// </summary>
	public partial class EtalonElectronicCompoentsTypes
	{
		
		internal EtalonElectronicCompoentsTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Эталоны электронных компонентов"
		/// </summary>
		public EtalonElectronicCompoentsType EtalonElectronicCompoentsReferenceObject
		{
			get
			{
				return Find(Keys.EtalonElectronicCompoentsReferenceObject);
			}
		}
		
		protected override EtalonElectronicCompoentsType CreateClassObject(Guid classGuid)
		{
			return new EtalonElectronicCompoentsType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Эталоны электронных компонентов"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Эталоны электронных компонентов"
			/// </summary>
		   public static readonly Guid EtalonElectronicCompoentsReferenceObject = new Guid("c350cff6-961b-4af3-a759-2581b8278d4c");

		}
	}
}
