//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.EtalonElectronicCompoents
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.References.Links;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model.Parameters;
	
	
	/// <summary>
	/// Представляет объект справочника "Эталоны электронных компонентов"
	/// </summary>
	public partial class EtalonElectronicCompoentsReferenceObject
	{
		
		internal EtalonElectronicCompoentsReferenceObject(EtalonElectronicCompoentsReference reference) : 
				base(reference)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объекта
		/// </summary>
		public new EtalonElectronicCompoentsType Class
		{
			get
			{
				return ((EtalonElectronicCompoentsType)(base.Class));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Наименование"
		/// </summary>
		public StringParameter Name
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Name]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Тип электронного компонента"
		/// </summary>
		public GuidParameter TypeEleсtronicComponent
		{
			get
			{
				return ((GuidParameter)(this[FieldKeys.TypeEleсtronicComponent]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Обозначение"
		/// </summary>
		public StringParameter Denotation
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Denotation]));
			}
		}
		
		/// <summary>
		/// Возвращает или задаёт связанный объект справочника "Номенклатура ERP" по связи "Номенклатура ERP"
		/// </summary>
		public ReferenceObject Nomenclature
		{
			get
			{
				return GetObject(RelationKeys.Nomenclature);
			}
			set
			{
				SetLinkedObject(RelationKeys.Nomenclature, value);
			}
		}
		
		/// <summary>
		/// Возвращает связанные объекты справочника "Справочник эквивалентов MDM" по связи "Эквиваленты электронных компонентов MDM"
		/// </summary>
		public ReferenceObjectCollection Equivalent
		{
			get
			{
				return Links.ToMany[RelationKeys.Equivalent].Objects;
			}
		}
		
		/// <summary>
		/// Возвращает или задаёт связанный объект справочника "Электронная структура изделий" по связи "Электронная структура изделия"
		/// </summary>
		public ReferenceObject ESI
		{
			get
			{
				return GetObject(RelationKeys.ESI);
			}
			set
			{
				SetLinkedObject(RelationKeys.ESI, value);
			}
		}
		
		/// <summary>
		/// Подключает объект справочника "Справочник эквивалентов MDM" по связи "Эквиваленты электронных компонентов MDM"
		/// </summary>
		/// <param name="newLinkedObject">
		/// Подключаемый объект
		/// </param>
		/// <returns>
		/// Подключённый объект
		/// </returns>
		public ReferenceObject AddEquivalent(ReferenceObject newLinkedObject)
		{
			return AddLinkedObject(RelationKeys.Equivalent, newLinkedObject);
		}
		
		/// <summary>
		/// Отключает объект справочника "Справочник эквивалентов MDM" по связи "Эквиваленты электронных компонентов MDM"
		/// </summary>
		/// <param name="linkedObject">
		/// Связанный объект
		/// </param>
		/// <returns>
		/// true, если объект был отключен
		/// </returns>
		public Boolean RemoveEquivalent(ReferenceObject linkedObject)
		{
			return RemoveLinkedObject(RelationKeys.Equivalent, linkedObject);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) параметров справочника "Эталоны электронных компонентов"
		/// </summary>
		public class FieldKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Наименование"
			/// </summary>
		   public static readonly Guid Name = new Guid("11526cb6-5f2f-4866-b9ab-7e2e72444b86");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Тип электронного компонента"
			/// </summary>
		   public static readonly Guid TypeEleсtronicComponent = new Guid("0a087ab9-443b-4c62-a6fb-1dae9f8ac3ee");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Обозначение"
			/// </summary>
		   public static readonly Guid Denotation = new Guid("370c870a-018d-437f-bb3f-50d6ce987f05");

		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) связей и списков объектов справочника "Эталоны электронных компонентов"
		/// </summary>
		public class RelationKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Номенклатура ERP"
			/// </summary>
		   public static readonly Guid Nomenclature = new Guid("a8d3a880-af21-481c-9c9d-31700d618394");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Эквиваленты электронных компонентов MDM"
			/// </summary>
		   public static readonly Guid Equivalent = new Guid("82834efb-e576-4aa0-85d1-147aa80475ac");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Электронная структура изделия"
			/// </summary>
		   public static readonly Guid ESI = new Guid("bfe5cd1e-0955-4b72-ad8d-e0f79dc798bc");

		}
	}
}
