//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.EtalonElectronicCompoents
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Эталоны электронных компонентов"
	/// </summary>
	public partial class EtalonElectronicCompoentsReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Эталоны электронных компонентов"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("aa0ef355-8b58-4fae-a9c9-5e2d56a7e166");
		
		/// <summary>
		/// Инициализирует новый экземпляр EtalonElectronicCompoentsReference для работы с объектами справочника "Эталоны электронных компонентов"
		/// </summary>
		public EtalonElectronicCompoentsReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, EtalonElectronicCompoentsReference.ReferenceId)
		{
		}
		
		private EtalonElectronicCompoentsReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Эталоны электронных компонентов"
		/// </summary>
		public new EtalonElectronicCompoentsTypes Classes
		{
			get
			{
				return ((EtalonElectronicCompoentsTypes)(base.Classes));
			}
		}
		
		protected override EtalonElectronicCompoentsReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			EtalonElectronicCompoentsType type = classObject as EtalonElectronicCompoentsType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsEtalonElectronicCompoentsReferenceObject)
			{
				return new EtalonElectronicCompoentsReferenceObject(this);
			}
			return new EtalonElectronicCompoentsReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<EtalonElectronicCompoentsReference, EtalonElectronicCompoentsTypes>
		{
			
			internal Factory()
			{
			}
			
			public override EtalonElectronicCompoentsReference CreateReference(ParameterGroup masterGroup)
			{
				return new EtalonElectronicCompoentsReference(masterGroup);
			}
			
			public override EtalonElectronicCompoentsTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new EtalonElectronicCompoentsTypes(masterGroup);
			}
		}
	}
}
