//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.ReplacementERP
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.References.Links;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model.Parameters;
	
	
	/// <summary>
	/// Представляет объект справочника "Замены ERP"
	/// </summary>
	public partial class ReplacementERPReferenceObject
	{
		
		internal ReplacementERPReferenceObject(ReplacementERPReference reference) : 
				base(reference)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объекта
		/// </summary>
		public new ReplacementERPType Class
		{
			get
			{
				return ((ReplacementERPType)(base.Class));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Номенклатура ERP-Заменяемый объект"
		/// </summary>
		public GuidParameter NomenclatureGuid
		{
			get
			{
				return ((GuidParameter)(this[FieldKeys.NomenclatureGuid]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Номенклатура ERP-Заменитель"
		/// </summary>
		public GuidParameter ReplacementNomenclatureGuid
		{
			get
			{
				return ((GuidParameter)(this[FieldKeys.ReplacementNomenclatureGuid]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Номенклатура ERP-Применяемость"
		/// </summary>
		public GuidParameter ApplicabilityNomanclatureGuid
		{
			get
			{
				return ((GuidParameter)(this[FieldKeys.ApplicabilityNomanclatureGuid]));
			}
		}
		
		/// <summary>
		/// Возвращает или задаёт связанный объект справочника "Номенклатура ERP" по связи "Заменяемый объект"
		/// </summary>
		public ReferenceObject NomenclatureERP
		{
			get
			{
				return GetObject(RelationKeys.NomenclatureERP);
			}
			set
			{
				SetLinkedObject(RelationKeys.NomenclatureERP, value);
			}
		}
		
		/// <summary>
		/// Возвращает или задаёт связанный объект справочника "Номенклатура ERP" по связи "Заменитель"
		/// </summary>
		public ReferenceObject ReplacementNomenclatureERP
		{
			get
			{
				return GetObject(RelationKeys.ReplacementNomenclatureERP);
			}
			set
			{
				SetLinkedObject(RelationKeys.ReplacementNomenclatureERP, value);
			}
		}
		
		/// <summary>
		/// Возвращает или задаёт связанный объект справочника "Номенклатура ERP" по связи "Применяемость в ERP"
		/// </summary>
		public ReferenceObject ApplicabilityNomenclatureERP
		{
			get
			{
				return GetObject(RelationKeys.ApplicabilityNomenclatureERP);
			}
			set
			{
				SetLinkedObject(RelationKeys.ApplicabilityNomenclatureERP, value);
			}
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) параметров справочника "Замены ERP"
		/// </summary>
		public class FieldKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Номенклатура ERP-Заменяемый объект"
			/// </summary>
		   public static readonly Guid NomenclatureGuid = new Guid("ecf356f5-305c-456a-99ba-1044f49f9afd");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Номенклатура ERP-Заменитель"
			/// </summary>
		   public static readonly Guid ReplacementNomenclatureGuid = new Guid("b8fc4a5e-f646-486a-8efe-7abfb127d5f1");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Номенклатура ERP-Применяемость"
			/// </summary>
		   public static readonly Guid ApplicabilityNomanclatureGuid = new Guid("ad01812f-29e5-4050-a1a2-2a845aea60c8");

		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) связей и списков объектов справочника "Замены ERP"
		/// </summary>
		public class RelationKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Заменяемый объект"
			/// </summary>
		   public static readonly Guid NomenclatureERP = new Guid("43bb2d60-0eb0-47a8-af72-a21fc00428b4");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Заменитель"
			/// </summary>
		   public static readonly Guid ReplacementNomenclatureERP = new Guid("3024a058-982a-4f07-b218-b37fa45fe155");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Применяемость в ERP"
			/// </summary>
		   public static readonly Guid ApplicabilityNomenclatureERP = new Guid("daed7c29-692d-4af0-b801-a36679099b0f");

		}
	}
}
