//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.NomenclatureERP
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Номенклатура ERP"
	/// </summary>
	public partial class NomenclatureERPType
	{
		
		internal NomenclatureERPType(NomenclatureERPTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Номенклатура ERP"
		/// </summary>
		public new NomenclatureERPTypes Classes
		{
			get
			{
				return ((NomenclatureERPTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Номенклатура ERP" или порождён от него
		/// </summary>
		public bool IsNomenclatureERPReferenceObject
		{
			get
			{
				return IsInherit(NomenclatureERPTypes.Keys.NomenclatureERPReferenceObject);
			}
		}
	}
}
