//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.NomenclatureERP
{
    using System;
    using TFlex.DOCs.Model.References;
    using TFlex.DOCs.Model.Structure;
    using TFlex.DOCs.Model.References.Links;
    using TFlex.DOCs.Model.Classes;
    using TFlex.DOCs.Model.Parameters;


    /// <summary>
    /// Представляет объект справочника "Номенклатура ERP"
    /// </summary>
    public partial class NomenclatureMDMReferenceObject
    {

        internal NomenclatureMDMReferenceObject(NomenclatureMDMReference reference) :
                base(reference)
        {
        }

        /// <summary>
        /// Возвращает описание типа объекта
        /// </summary>
        public new NomenclatureMDMType Class
        {
            get
            {
                return ((NomenclatureMDMType)(base.Class));
            }
        }

        /// <summary>
        /// Возвращает параметр "Наименование"
        /// </summary>
        public StringParameter Name
        {
            get
            {
                return ((StringParameter)(this[FieldKeys.Name]));
            }
        }

        /// <summary>
        /// Возвращает параметр "Обозначение"
        /// </summary>
        public StringParameter Denotation
        {
            get
            {
                return ((StringParameter)(this[FieldKeys.Denotation]));
            }
        }

        /// <summary>
        /// Возвращает параметр "Вес"
        /// </summary>
        public DoubleParameter Weight
        {
            get
            {
                return ((DoubleParameter)(this[FieldKeys.Weight]));
            }
        }

        /// <summary>
        /// Возвращает параметр "GUID(1C)"
        /// </summary>
        public GuidParameter GUID1C
        {
            get
            {
                return ((GuidParameter)(this[FieldKeys.GUID1C]));
            }
        }

        /// <summary>
        /// Возвращает параметр "GUID(T-FLEX)"
        /// </summary>
        public GuidParameter GUIDTFLEX
        {
            get
            {
                return ((GuidParameter)(this[FieldKeys.GUIDTFLEX]));
            }
        }

        /// <summary>
        /// Возвращает параметр "КодЕламед"
        /// </summary>
        public StringParameter CodeElamed
        {
            get
            {
                return (StringParameter)this[FieldKeys.CodeElamed];
            }
        }

        /// <summary>
        /// Возвращает параметр "Типовое"
        /// </summary>
        public BooleanParameter IsTypical
        {
            get
            {
                return (BooleanParameter)this[FieldKeys.IsTypical];
            }
        }

        /// <summary>
        /// Возвращает значение параметра "Актуальность записи"
        /// </summary>
        public bool IsActual
        {
            get
            {
                return ((BooleanParameter)this[FieldKeys.IsActual]).Value;
            }
        }
        /// <summary>
        /// Задать значение актуальности 
        /// </summary>
        /// <param name="flag"></param>
        public void SetActual(bool flag) {
            this[FieldKeys.IsActual].Value = flag;
        }

        /// <summary>
        /// Возвращает или задаёт связанный объект справочника "Товарные категории изделий" по связи "Товарная категория"
        /// </summary>
        public ReferenceObject ProductCategory
        {
            get
            {
                return GetObject(RelationKeys.ProductCategory);
            }
            set
            {
                SetLinkedObject(RelationKeys.ProductCategory, value);
            }
        }

        /// <summary>
        /// Возвращает или задаёт связанный объект справочника "Группы списка" по связи "Группа списка"
        /// </summary>
        public ReferenceObject GroupList
        {
            get
            {
                return GetObject(RelationKeys.GroupList);
            }
            set
            {
                SetLinkedObject(RelationKeys.GroupList, value);
            }
        }

        /// <summary>
        /// Возвращает или задает связанный объект справочника "Группа финансового учета номенклатуры"
        /// </summary>
        public ReferenceObject GroupFinanceNomenclature
        {
            get
            {
                return GetObject(RelationKeys.GroupFinanceNomenclature);
            }
            set
            {
                SetLinkedObject(RelationKeys.GroupFinanceNomenclature, value);
            }
        }
        /// <summary>
        /// Возвращает или задаёт связанный объект справочника "Типы воспроизводства" по связи "Тип воспроизводства"
        /// </summary>
        public ReferenceObject TypeReproduction
        {
            get
            {
                return GetObject(RelationKeys.TypeReproduction);
            }
            set
            {
                SetLinkedObject(RelationKeys.TypeReproduction, value);
            }
        }

        /// <summary>
        /// Возвращает или задаёт связанный объект справочника "Типы номенклатуры" по связи "Тип номенклатуры"
        /// </summary>
        public ReferenceObject TypeNomenclature
        {
            get
            {
                return GetObject(RelationKeys.TypeNomenclature);
            }
            set
            {
                SetLinkedObject(RelationKeys.TypeNomenclature, value);
            }
        }

        /// <summary>
        /// Возвращает или задаёт связанный объект справочника "Единицы измерения 1C" по связи "Единица измерения"
        /// </summary>
        public ReferenceObject UnitsOfMeasurement
        {
            get
            {
                return GetObject(RelationKeys.UnitsOfMeasurement);
            }
            set
            {
                SetLinkedObject(RelationKeys.UnitsOfMeasurement, value);
            }
        }

        /// <summary>
        /// Возвращает или задаёт связанный объект справочника "Единицы измерения 1C" по связи "Единицы измерения веса"
        /// </summary>
        public ReferenceObject UnitOfMeasurementWeight
        {
            get
            {
                return GetObject(RelationKeys.UnitOfMeasurementWeight);
            }
            set
            {
                SetLinkedObject(RelationKeys.UnitOfMeasurementWeight, value);
            }
        }

        /// <summary>
        /// Возвращает или задаёт связанный объект справочника "Электронная структура изделий" по связи "Номенклатура"
        /// </summary>
        public ReferenceObject Nomenclature
        {
            get
            {
                return GetObject(RelationKeys.Nomenclature);
            }
            set
            {
                SetLinkedObject(RelationKeys.Nomenclature, value);
            }
        }

        /// <summary>
		/// Возвращает объекты списка "Единицы измерения"
		/// </summary>
        public ReferenceObjectCollection UnitsOfMeasurementList
        {
            get
            {
                return Links.ToMany[RelationKeys.UnitsOfMeasurement].Objects;
            }
        }

        /// <summary>
        /// Возвращает объекты списка "Единицы"
        /// </summary>
        public ReferenceObjectCollection UnitsList
        {
            get
            {
                return Links.ToMany[RelationKeys.UnitsList].Objects;
            }
        }
        /// <summary>
        /// Возвращает или задаёт связанный объект справочника "Применение материала" по связи "Используемые материалы"
        /// </summary>
        //public ReferenceObject MaterialUsed
        //{
        //    get
        //    {
        //        return GetObject(RelationKeys.MaterialUsed);
        //    }
        //    set
        //    {
        //        SetLinkedObject(RelationKeys.MaterialUsed, value);
        //    }
        //}

        /// <summary>
        /// Возвращает или задаёт связанный объекты справочника "Применение материала" по связи "Используемые материалы"
        /// </summary>
        //public ReferenceObjectCollection MaterialsUsed
        //{
        //    get
        //    {
        //        return Links.ToMany[RelationKeys.MaterialUsed].Objects;
        //    }
        //}
        /// <summary>
        /// Подключает объект справочника "Применение материалов" по связи "Используемые материалы"
        /// </summary>
        /// <param name="addObject">
        /// Подключаемый объект
        /// </param>
        /// <returns>
        /// Подключённый объект
        /// </returns>
        //public ReferenceObject AddMaterialUsed(ReferenceObject addObject)
        //{
        //    return AddLinkedObject(RelationKeys.MaterialUsed, addObject);
        //}

        /// <summary>
        /// Отключает объект справочника "Номенклатура ERP" по связи "Набор подключений"
        /// </summary>
        /// <param name="linkedObject">
        /// Связанный объект
        /// </param>
        /// <returns>
        /// true, если объект был отключен
        /// </returns>
        //public Boolean RemoveMaterialUsed(ReferenceObject linkedObject)
        //      {
        //          return RemoveLinkedObject(RelationKeys.MaterialUsed, linkedObject);
        //      }

        /// <summary>
        /// Уникальные идентификаторы (GUID) параметров справочника "Номенклатура ERP"
        /// </summary>
        public class FieldKeys
        {

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) параметра "Наименование"
            /// </summary>
            public static readonly Guid Name = new Guid("0cd50190-89d3-42bc-ac86-0910eee00d80");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) параметра "Обозначение"
            /// </summary>
            public static readonly Guid Denotation = new Guid("d3c3f4eb-011b-4e3f-a9ab-5c612d8ddc6d");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) параметра "Вес"
            /// </summary>
            public static readonly Guid Weight = new Guid("686d7cf4-c559-4cfb-b775-09df19b4ffe8");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) параметра "GUID(1C)"
            /// </summary>
            public static readonly Guid GUID1C = new Guid("674e6c4d-a713-4a92-94aa-3b3eeb09bcd0");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) параметра "GUID(T-FLEX)"
            /// </summary>
            public static readonly Guid GUIDTFLEX = new Guid("4dfaf3ee-e47f-44cc-8dca-8da8b4a0e4a6");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) параметра "КодЕламед"
            /// </summary>
            public readonly static Guid CodeElamed = new Guid("249171d8-0b8a-4623-9072-8cbbcbe00934");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) параметра "Типовое"
            /// </summary>
            public readonly static Guid IsTypical = new Guid("6602adfc-6ade-4eda-978e-363362a7babe");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) параметра "Актуальность записи"
            /// </summary>
            public readonly static Guid IsActual = new Guid("50efae15-8902-4a6f-9cc8-e7da07abbb58");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) параметра "НаименованиеДляВвода"
            /// </summary>
            public static readonly Guid NameForInput = new Guid("9753e16c-53b2-434f-9d6e-2facfd020e84");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) параметра "НаименованиеПолное"
            /// </summary>
            public static readonly Guid NameFull = new Guid("53b0e4b0-96b6-490c-852e-c69ba72fba99");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) параметра "ID53"
            /// </summary>
            public static readonly Guid ID53 = new Guid("1b97331b-373e-46aa-93aa-fc07467a1154");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) параметра "Артикул"
            /// </summary>
            public static readonly Guid Articul = new Guid("e6a7cdff-23e5-4d35-91f4-f2889f8859f0");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) параметра "Код"
            /// </summary>
            public static readonly Guid Code = new Guid("675d4b1f-e154-4737-89e7-1a9f78cceb78");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) параметра "Вид воспроизводства"
            /// </summary>
            public static readonly Guid TypeReproduction = new Guid("a20ce066-638c-4712-8f0d-ef4b50e49f18");

        }

        /// <summary>
        /// Уникальные идентификаторы (GUID) связей и списков объектов справочника "Номенклатура ERP"
        /// </summary>
        public class RelationKeys
        {

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Товарная категория"
            /// </summary>
            public static readonly Guid ProductCategory = new Guid("a45a8a4e-3ad5-4959-b90b-f1e75ec1116f");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Группа списка"
            /// </summary>
            public static readonly Guid GroupList = new Guid("0c8c7a41-4b54-41cd-9774-0cc900e113fe");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Тип воспроизводства"
            /// </summary>
            public static readonly Guid TypeReproduction = new Guid("dd89ae41-e111-4981-aff6-06918e5db036");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Тип номенклатуры"
            /// </summary>
            public static readonly Guid TypeNomenclature = new Guid("384b10fc-a257-4fea-b130-c1a035a630cd");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Единица измерения"
            /// </summary>
            public static readonly Guid UnitsOfMeasurement = new Guid("3cdc128c-486e-4234-8fa6-62c248790516");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Номенклатура"
            /// </summary>
            public static readonly Guid Nomenclature = new Guid("b0c79258-a68e-486c-8470-1bf272466ad5");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Входящая номенклатура" Детали и сборки НСИ
            /// </summary>
            public static readonly Guid InputNomenclatureDSE = new Guid("f6d1aeae-7183-4269-b65c-1722f997a838");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Входящая номенклатура" заготовки НСИ
            /// </summary>
            public static readonly Guid InputNomenclatureBlank = new Guid("56d6635d-a4c2-443d-ae83-af37b00cc54c");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Входящая номенклатура" изделие НСИ
            /// </summary>
            public static readonly Guid InputNomenclatureProduct = new Guid("144268b3-c6c1-426e-aab3-6d1fb5fcb0ae");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Входящая номенклатура" материалы НСИ
            /// </summary>
            public static readonly Guid InputNomenclatureMaterial = new Guid("0832726f-a2e7-4045-b35b-fb2c938520c1");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Входящая номенклатура" ОМ НСИ
            /// </summary>
            public static readonly Guid InputNomenclatureOM = new Guid("8318119c-d6ab-4e78-893b-d87c4f8671a5");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Входящая номенклатура" Прочие изделия НСИ
            /// </summary>
            public static readonly Guid InputNomenclatureOtherProduct = new Guid("7c4b9d7a-787d-4d73-b1b2-f51c072eb662");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Входящая номенклатура" стандартные изделия НСИ
            /// </summary>
            public static readonly Guid InputNomenclatureStandartProduct = new Guid("159d42ca-fb94-43ed-b3ca-bf0558a679f1");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "НСИ электронные компоненты"
            /// </summary>
            public static readonly Guid InputNomenclatureElectronComponent = new Guid("9ab44ecd-df1c-4821-bf41-7f08f2ea828f");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Материал" Применение материала
            /// </summary>
            public static readonly Guid Link_3509_3496 = new Guid("021ce6a8-5229-4b11-8d0a-e633b8a0a475");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Заменяемый объект" Замены ERP
            /// </summary>
            public static readonly Guid NomenclatureReplaceable = new Guid("43bb2d60-0eb0-47a8-af72-a21fc00428b4");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Заменитель" Замена ERP
            /// </summary>
            public static readonly Guid NomenclatureReplacement = new Guid("3024a058-982a-4f07-b218-b37fa45fe155");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Набор подключений"
            /// </summary>
            public static readonly Guid Link_3513_3496 = new Guid("04d3917e-0441-47cc-967b-4319f176fd31");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Текущий объект"
            /// </summary>
            public static readonly Guid Link_3512_3496 = new Guid("ac93d4dd-cbe0-4bfe-af35-4765a600952b");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Дочерний объект"
            /// </summary>
            public static readonly Guid Link_3512_3496_1 = new Guid("8c366b36-6284-49c5-8e5a-17d48ec3a10d");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Эталон электронных компонентов"
            /// </summary>
            public static readonly Guid EtalonElectricalComponents = new Guid("a8d3a880-af21-481c-9c9d-31700d618394");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Эталон стандартные изделия"
            /// </summary>
            public static readonly Guid EtalonStandartProduct = new Guid("917c19a0-6267-4ade-a87c-a4980ec54542");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Эталон прочие изделия" 
            /// </summary>
            public static readonly Guid EtalonOtherProduct = new Guid("75c5ae89-176a-4adf-a7f9-0b3d49fb319a");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Эталон оригинал макеты"
            /// </summary>
            public static readonly Guid EtalonOM = new Guid("1531fa73-d8a6-4347-83c3-cc8ac233eaa5");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Эталон материалы"
            /// </summary>
            public static readonly Guid EtalonMaterial = new Guid("b90e41e3-2160-4f7e-ae86-4c55345306fc");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Эталон изделия"
            /// </summary>
            public static readonly Guid EtalonProduct = new Guid("730906d9-055c-483e-824f-d9ad6856d1db");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Эталон детали и сборки"
            /// </summary>
            public static readonly Guid EtalonDSE = new Guid("8a3eafb2-2442-4556-82a8-58ea50ee690e");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Эталон заготовки"
            /// </summary>
            public static readonly Guid EtalonBlank = new Guid("b83e8813-4bb8-4bab-b9e0-e22945c60bcf");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Текущий объект" подключение номенклатур Link_3512_3496_2
            /// </summary>
            public static readonly Guid CurrentObject = new Guid("cda1e218-5dbb-485a-b35f-df920ebd8ca6");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Дочерний объект" подключение номенклатур Link_3512_3496_3 Подключение номенклатур
            /// </summary>
            public static readonly Guid ChildrenObjects = new Guid("00678c93-cd81-4a0c-88e7-c4775da7f976");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Предпросмотр структуры"
            /// </summary>
            public static readonly Guid ObjectInPreview = new Guid("670ed240-7256-4aeb-8da8-1245f085d7c0");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Применяемость в ERP" Замены ERP
            /// </summary>
            public static readonly Guid ApplicabilityNomenclature = new Guid("daed7c29-692d-4af0-b801-a36679099b0f");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Единицы измерения веса" Единицы измерения веса
            /// </summary>
            public static readonly Guid UnitOfMeasurementWeight = new Guid("c90cdee4-2b83-4d9c-8010-ab245d265b21");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Материал"
            /// </summary>
            public static readonly Guid Link_3509_3496_1 = new Guid("c3000bc7-35a3-4e6b-aec1-0e67eed6079b");



            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Используемые материалы"
            /// </summary>
            //public static readonly Guid MaterialUsed = new Guid("f4216316-ce4f-4017-8cab-9a701817ee9b");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Группа финансового учета номенклатуры"
            /// </summary>
            public static readonly Guid GroupFinanceNomenclature = new Guid("4d8bbde9-bd7d-4565-a437-b2b21baf84df");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Руководство по эксплуатации НСИ"
            /// </summary>
            public static readonly Guid InputNomenclatureUserManual = new Guid("516d921f-ca06-4330-a932-650e86561eb1");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Эталон руководств по эксплуатации ERP"
            /// </summary>
            public static readonly Guid EtalonUserManual = new Guid("fda93048-e2db-4fed-94c1-794d5cc405ba");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Маршрут"
            /// </summary>
            public static readonly Guid Route = new Guid("2396c3eb-180e-44e3-af72-e5613fc7ef0a");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Вид учета ТМЦ"
            /// </summary>
            public static readonly Guid TypeRecordTMC = new Guid("16a38cef-325a-4f11-a8e3-9b644d75d05b");

            /// <summary>
			/// Представляет уникальный идентификатор (GUID) списка объектов "Единицы измерения"
			/// </summary>
            public static readonly Guid UnitsOfMeasurementList = new Guid("a997ffb6-7d44-40ad-81df-9a3d7396dee2");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) списка объектов "Единицы"
            /// </summary>
            public static readonly Guid UnitsList = new Guid("de540b61-fd8d-4664-bb86-3648cdc6b14d");

        }
    }
}
