//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.NomenclatureERP
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Номенклатура ERP"
	/// </summary>
	public partial class NomenclatureERPTypes
	{
		
		internal NomenclatureERPTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Номенклатура ERP"
		/// </summary>
		public NomenclatureERPType NomenclatureERPReferenceObject
		{
			get
			{
				return Find(Keys.NomenclatureERPReferenceObject);
			}
		}
		
		protected override NomenclatureERPType CreateClassObject(Guid classGuid)
		{
			return new NomenclatureERPType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Номенклатура ERP"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Номенклатура ERP"
			/// </summary>
		   public static readonly Guid NomenclatureERPReferenceObject = new Guid("9ab08dd5-1cdf-499c-9442-0723236053a8");

		}
	}
}
