//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.NomenclatureERP
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Номенклатура ERP"
	/// </summary>
	public partial class NomenclatureERPReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Номенклатура ERP"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("93c1524e-1e80-4532-9a94-3d2ec65320c1");
		
		/// <summary>
		/// Инициализирует новый экземпляр NomenclatureERPReference для работы с объектами справочника "Номенклатура ERP"
		/// </summary>
		public NomenclatureERPReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, NomenclatureERPReference.ReferenceId)
		{
			loadSupportReference();
		}
		
		private NomenclatureERPReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
			loadSupportReference();
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Номенклатура ERP"
		/// </summary>
		public new NomenclatureERPTypes Classes
		{
			get
			{
				return ((NomenclatureERPTypes)(base.Classes));
			}
		}
		
		protected override NomenclatureERPReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			NomenclatureERPType type = classObject as NomenclatureERPType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsNomenclatureERPReferenceObject)
			{
				return new NomenclatureERPReferenceObject(this);
			}
			return new NomenclatureERPReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<NomenclatureERPReference, NomenclatureERPTypes>
		{
			
			internal Factory()
			{
			}
			
			public override NomenclatureERPReference CreateReference(ParameterGroup masterGroup)
			{
				return new NomenclatureERPReference(masterGroup);
			}
			
			public override NomenclatureERPTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new NomenclatureERPTypes(masterGroup);
			}
		}
	}
}
