//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.MDM.Rank
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Разряд работ"
	/// </summary>
	public partial class RankMDMType
	{
		
		internal RankMDMType(RankMDMTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Разряд работ"
		/// </summary>
		public new RankMDMTypes Classes
		{
			get
			{
				return ((RankMDMTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Разряд работ" или порождён от него
		/// </summary>
		public bool IsMainRankRype
		{
			get
			{
				return IsInherit(RankMDMTypes.Keys.MainRankRype);
			}
		}
	}
}
