//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.Rank
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Разряд работ"
	/// </summary>
	public partial class RankReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Разряд работ"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("862578ee-a916-4db6-8753-13dc61520ede");
		
		/// <summary>
		/// Инициализирует новый экземпляр RankReference для работы с объектами справочника "Разряд работ"
		/// </summary>
		public RankReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, RankReference.ReferenceId)
		{
		}
		
		private RankReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Разряд работ"
		/// </summary>
		public new RankTypes Classes
		{
			get
			{
				return ((RankTypes)(base.Classes));
			}
		}
		
		protected override RankReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			RankType type = classObject as RankType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsMainRankRype)
			{
				return new RankReferenceObject(this);
			}
			return new RankReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<RankReference, RankTypes>
		{
			
			internal Factory()
			{
			}
			
			public override RankReference CreateReference(ParameterGroup masterGroup)
			{
				return new RankReference(masterGroup);
			}
			
			public override RankTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new RankTypes(masterGroup);
			}
		}
	}
}
