//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.TypeTMC
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Вид учета ТМЦ"
	/// </summary>
	public partial class TypeTMCTypes
	{
		
		internal TypeTMCTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Вид учета ТМЦ"
		/// </summary>
		public TypeTMCType TypeTMC
		{
			get
			{
				return Find(Keys.TypeTMC);
			}
		}
		
		protected override TypeTMCType CreateClassObject(Guid classGuid)
		{
			return new TypeTMCType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Вид учета ТМЦ"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Вид учета ТМЦ"
			/// </summary>
		   public static readonly Guid TypeTMC = new Guid("605ef014-4366-454f-8e1c-48995e1e0ce9");

		}
	}
}
