//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.TypeTMC
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Вид учета ТМЦ"
	/// </summary>
	public partial class TypeTMCType
	{
		
		internal TypeTMCType(TypeTMCTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Вид учета ТМЦ"
		/// </summary>
		public new TypeTMCTypes Classes
		{
			get
			{
				return ((TypeTMCTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Вид учета ТМЦ" или порождён от него
		/// </summary>
		public bool IsTypeTMC
		{
			get
			{
				return IsInherit(TypeTMCTypes.Keys.TypeTMC);
			}
		}
	}
}
