//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.TypeTMC
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.References.Links;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model.Parameters;
	
	
	/// <summary>
	/// Представляет объект справочника "Вид учета ТМЦ"
	/// </summary>
	public partial class TypeTMCReferenceObject
	{
		
		internal TypeTMCReferenceObject(TypeTMCReference reference) : 
				base(reference)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объекта
		/// </summary>
		public new TypeTMCType Class
		{
			get
			{
				return ((TypeTMCType)(base.Class));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Наименование"
		/// </summary>
		public StringParameter Name
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Name]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "UID 1C"
		/// </summary>
		public StringParameter UID1C
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.UID1C]));
			}
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) параметров справочника "Вид учета ТМЦ"
		/// </summary>
		public class FieldKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Наименование"
			/// </summary>
		   public static readonly Guid Name = new Guid("1cc679ad-895d-4503-9339-0264b607bca4");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "UID 1C"
			/// </summary>
		   public static readonly Guid UID1C = new Guid("61b41bda-b652-400d-bebe-db1dfde1ad11");

		}
	}
}
