//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.FilterProduct
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Изделия НСИ"
	/// </summary>
	public partial class FilterProductTypes
	{
		
		internal FilterProductTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Изделия НСИ"
		/// </summary>
		public FilterProductType FilterProductReferenceObject
		{
			get
			{
				return Find(Keys.FilterProductReferenceObject);
			}
		}
		
		protected override FilterProductType CreateClassObject(Guid classGuid)
		{
			return new FilterProductType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Изделия НСИ"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Изделия НСИ"
			/// </summary>
		   public static readonly Guid FilterProductReferenceObject = new Guid("dc7b6e1b-39cf-4161-86f4-c7e21ed38114");

		}
	}
}
