//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.FilterProduct
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Изделия НСИ"
	/// </summary>
	public partial class FilterProductReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Изделия НСИ"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("795e9f05-852b-46ae-bc9f-7b8034e00656");
		
		/// <summary>
		/// Инициализирует новый экземпляр FilterProductReference для работы с объектами справочника "Изделия НСИ"
		/// </summary>
		public FilterProductReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, FilterProductReference.ReferenceId)
		{
		}
		
		private FilterProductReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Изделия НСИ"
		/// </summary>
		public new FilterProductTypes Classes
		{
			get
			{
				return ((FilterProductTypes)(base.Classes));
			}
		}
		
		protected override FilterProductReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			FilterProductType type = classObject as FilterProductType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsFilterProductReferenceObject)
			{
				return new FilterProductReferenceObject(this);
			}
			return new FilterProductReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<FilterProductReference, FilterProductTypes>
		{
			
			internal Factory()
			{
			}
			
			public override FilterProductReference CreateReference(ParameterGroup masterGroup)
			{
				return new FilterProductReference(masterGroup);
			}
			
			public override FilterProductTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new FilterProductTypes(masterGroup);
			}
		}
	}
}
