//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.TypeOperationMDM
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Вид техоперации"
	/// </summary>
	public partial class TypeOperationMDMType
	{
		
		internal TypeOperationMDMType(TypeOperationMDMTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Вид техоперации"
		/// </summary>
		public new TypeOperationMDMTypes Classes
		{
			get
			{
				return ((TypeOperationMDMTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Вид техоперации" или порождён от него
		/// </summary>
		public bool IsMainTypeOperation
		{
			get
			{
				return IsInherit(TypeOperationMDMTypes.Keys.MainTypeOperation);
			}
		}
	}
}
