//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.TypeOperationMDM
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Вид техоперации"
	/// </summary>
	public partial class TypeOperationMDMTypes
	{
		
		internal TypeOperationMDMTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Вид техоперации"
		/// </summary>
		public TypeOperationMDMType MainTypeOperation
		{
			get
			{
				return Find(Keys.MainTypeOperation);
			}
		}
		
		protected override TypeOperationMDMType CreateClassObject(Guid classGuid)
		{
			return new TypeOperationMDMType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Вид техоперации"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Вид техоперации"
			/// </summary>
		   public static readonly Guid MainTypeOperation = new Guid("82b8710e-64e5-409e-a6a7-e34471a04d23");

		}
	}
}
