//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.TypeOperationMDM
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.References.Links;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model.Parameters;
	
	
	/// <summary>
	/// Представляет объект справочника "Вид техоперации"
	/// </summary>
	public partial class TypeOperationMDMReferenceObject
	{
		
		internal TypeOperationMDMReferenceObject(TypeOperationMDMReference reference) : 
				base(reference)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объекта
		/// </summary>
		public new TypeOperationMDMType Class
		{
			get
			{
				return ((TypeOperationMDMType)(base.Class));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Наименование"
		/// </summary>
		public StringParameter Name
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Name]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Код"
		/// </summary>
		public StringParameter Kod
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Kod]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "UID"
		/// </summary>
		public StringParameter UID
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.UID]));
			}
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) параметров справочника "Вид техоперации"
		/// </summary>
		public class FieldKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Наименование"
			/// </summary>
		   public static readonly Guid Name = new Guid("9dfb8365-46bc-4602-81d3-0d240e296c98");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Код"
			/// </summary>
		   public static readonly Guid Kod = new Guid("20ab22f2-f711-4e12-8e52-f6f73114683e");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "UID"
			/// </summary>
		   public static readonly Guid UID = new Guid("ff400141-f171-40aa-ae1b-9170fca7340f");

		}
	}
}
