//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.Performers
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.References.Links;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model.Parameters;
	
	
	/// <summary>
	/// Представляет объект справочника "Исполнители операции"
	/// </summary>
	public partial class PerformersReferenceObject
	{
		
		internal PerformersReferenceObject(PerformersReference reference) : 
				base(reference)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объекта
		/// </summary>
		public new PerformersType Class
		{
			get
			{
				return ((PerformersType)(base.Class));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Наименование"
		/// </summary>
		public StringParameter Name
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Name]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Количество рабочих"
		/// </summary>
		public Int32Parameter WorkersCount
		{
			get
			{
				return ((Int32Parameter)(this[FieldKeys.WorkersCount]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Коэффициент штучного времени"
		/// </summary>
		public DoubleParameter TimeKoef
		{
			get
			{
				return ((DoubleParameter)(this[FieldKeys.TimeKoef]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Подготовительно-заключительное время"
		/// </summary>
		public DoubleParameter PrepTime
		{
			get
			{
				return ((DoubleParameter)(this[FieldKeys.PrepTime]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Разряд рабочего"
		/// </summary>
		public Int32Parameter Rank
		{
			get
			{
				return ((Int32Parameter)(this[FieldKeys.Rank]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Штучное время"
		/// </summary>
		public DoubleParameter PieceTime
		{
			get
			{
				return ((DoubleParameter)(this[FieldKeys.PieceTime]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Единица нормирования"
		/// </summary>
		public Int32Parameter RationingUnit
		{
			get
			{
				return ((Int32Parameter)(this[FieldKeys.RationingUnit]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Степень механизации"
		/// </summary>
		public Int32Parameter MechanizationLevel
		{
			get
			{
				return ((Int32Parameter)(this[FieldKeys.MechanizationLevel]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Условия труда"
		/// </summary>
		public Int32Parameter OccupationSafetyAndHealth
		{
			get
			{
				return ((Int32Parameter)(this[FieldKeys.OccupationSafetyAndHealth]));
			}
		}
		
		/// <summary>
		/// Возвращает или задаёт связанный объект справочника "Профессии" по связи "Профессия"
		/// </summary>
		public ReferenceObject PerformersToProfessions
		{
			get
			{
				return GetObject(RelationKeys.PerformersToProfessions);
			}
			set
			{
				SetLinkedObject(RelationKeys.PerformersToProfessions, value);
			}
		}
		
		/// <summary>
		/// Возвращает или задаёт связанный объект справочника "Технологические процессы" по связи "Операция"
		/// </summary>
		public ReferenceObject PerformersToOperationTP
		{
			get
			{
				return GetObject(RelationKeys.PerformersToOperationTP);
			}
			set
			{
				SetLinkedObject(RelationKeys.PerformersToOperationTP, value);
			}
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) параметров справочника "Исполнители операции"
		/// </summary>
		public class FieldKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Наименование"
			/// </summary>
		   public static readonly Guid Name = new Guid("3aeee076-2936-4d02-9b73-255234abb03f");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Количество рабочих"
			/// </summary>
		   public static readonly Guid WorkersCount = new Guid("c3683724-96d2-41f3-8f86-b60af501e2a7");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Коэффициент штучного времени"
			/// </summary>
		   public static readonly Guid TimeKoef = new Guid("6cc710c6-f32b-47b1-8c85-0d2aa46d38e9");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Подготовительно-заключительное время"
			/// </summary>
		   public static readonly Guid PrepTime = new Guid("de99ac65-e793-477d-a3da-e4a326352491");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Разряд рабочего"
			/// </summary>
		   public static readonly Guid Rank = new Guid("09d95af0-2bd7-4260-87c2-4179afb9c633");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Штучное время"
			/// </summary>
		   public static readonly Guid PieceTime = new Guid("c9b29378-2e28-4505-8755-e5c0a2c164f7");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Единица нормирования"
			/// </summary>
		   public static readonly Guid RationingUnit = new Guid("03ef3aa3-b7fa-4efe-89da-cded457e2903");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Степень механизации"
			/// </summary>
		   public static readonly Guid MechanizationLevel = new Guid("c0bb3c91-9bf4-41fc-9710-5eb8510f6bed");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Условия труда"
			/// </summary>
		   public static readonly Guid OccupationSafetyAndHealth = new Guid("63d68a8d-c33e-4d7c-8764-03248688187b");

		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) связей и списков объектов справочника "Исполнители операции"
		/// </summary>
		public class RelationKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Профессия"
			/// </summary>
		   public static readonly Guid PerformersToProfessions = new Guid("2f1acb06-b20a-4fe5-897f-045138476351");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Операция"
			/// </summary>
		   public static readonly Guid PerformersToOperationTP = new Guid("3a7eab57-39e7-4bb7-92dd-aaa791be9fc4");

		}
	}
}
