//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.Performers
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Исполнители операции"
	/// </summary>
	public partial class PerformersType
	{
		
		internal PerformersType(PerformersTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Исполнители операции"
		/// </summary>
		public new PerformersTypes Classes
		{
			get
			{
				return ((PerformersTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Исполнитель операции" или порождён от него
		/// </summary>
		public bool IsMainPerformers
		{
			get
			{
				return IsInherit(PerformersTypes.Keys.MainPerformers);
			}
		}
	}
}
