//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.Performers
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Исполнители операции"
	/// </summary>
	public partial class PerformersReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Исполнители операции"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("0c470782-0064-470d-b05d-7bb4aea4c6d6");
		
		/// <summary>
		/// Инициализирует новый экземпляр PerformersReference для работы с объектами справочника "Исполнители операции"
		/// </summary>
		public PerformersReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, PerformersReference.ReferenceId)
		{
		}
		
		private PerformersReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Исполнители операции"
		/// </summary>
		public new PerformersTypes Classes
		{
			get
			{
				return ((PerformersTypes)(base.Classes));
			}
		}
		
		protected override PerformersReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			PerformersType type = classObject as PerformersType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsMainPerformers)
			{
				return new PerformersReferenceObject(this);
			}
			return new PerformersReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<PerformersReference, PerformersTypes>
		{
			
			internal Factory()
			{
			}
			
			public override PerformersReference CreateReference(ParameterGroup masterGroup)
			{
				return new PerformersReference(masterGroup);
			}
			
			public override PerformersTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new PerformersTypes(masterGroup);
			}
		}
	}
}
