//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.EtalonDetailAndAssebly
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Эталонные детали и сборки"
	/// </summary>
	public partial class EtalonDetailAndAsseblingReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Эталонные детали и сборки"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("eb80bbc0-a57c-42cc-89ad-a970d2413a8f");
		
		/// <summary>
		/// Инициализирует новый экземпляр EtalonDetailAndAsseblyReference для работы с объектами справочника "Эталонные детали и сборки"
		/// </summary>
		public EtalonDetailAndAsseblingReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, EtalonDetailAndAsseblingReference.ReferenceId)
		{
		}
		
		private EtalonDetailAndAsseblingReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Эталонные детали и сборки"
		/// </summary>
		public new EtalonDetailAndAsseblingTypes Classes
		{
			get
			{
				return ((EtalonDetailAndAsseblingTypes)(base.Classes));
			}
		}
		
		protected override EtalonDetailAndAsseblingReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			EtalonDetailAndAsseblingType type = classObject as EtalonDetailAndAsseblingType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsEtalonDetailAndAsseblyReferenceObject)
			{
				return new EtalonDetailAndAsseblingReferenceObject(this);
			}
			return new EtalonDetailAndAsseblingReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<EtalonDetailAndAsseblingReference, EtalonDetailAndAsseblingTypes>
		{
			
			internal Factory()
			{
			}
			
			public override EtalonDetailAndAsseblingReference CreateReference(ParameterGroup masterGroup)
			{
				return new EtalonDetailAndAsseblingReference(masterGroup);
			}
			
			public override EtalonDetailAndAsseblingTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new EtalonDetailAndAsseblingTypes(masterGroup);
			}
		}
	}
}
