//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.EtalonDetailAndAssebly
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Эталонные детали и сборки"
	/// </summary>
	public partial class EtalonDetailAndAsseblingType
	{
		
		internal EtalonDetailAndAsseblingType(EtalonDetailAndAsseblingTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Эталонные детали и сборки"
		/// </summary>
		public new EtalonDetailAndAsseblingTypes Classes
		{
			get
			{
				return ((EtalonDetailAndAsseblingTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Эталонные детали и сборки" или порождён от него
		/// </summary>
		public bool IsEtalonDetailAndAsseblyReferenceObject
		{
			get
			{
				return IsInherit(EtalonDetailAndAsseblingTypes.Keys.EtalonDetailAndAsseblyReferenceObject);
			}
		}
	}
}
