//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.EtalonDetailAndAssebly
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Эталонные детали и сборки"
	/// </summary>
	public partial class EtalonDetailAndAsseblingTypes
	{
		
		internal EtalonDetailAndAsseblingTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Эталонные детали и сборки"
		/// </summary>
		public EtalonDetailAndAsseblingType EtalonDetailAndAsseblyReferenceObject
		{
			get
			{
				return Find(Keys.EtalonDetailAndAsseblyReferenceObject);
			}
		}
		
		protected override EtalonDetailAndAsseblingType CreateClassObject(Guid classGuid)
		{
			return new EtalonDetailAndAsseblingType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Эталонные детали и сборки"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Эталонные детали и сборки"
			/// </summary>
		   public static readonly Guid EtalonDetailAndAsseblyReferenceObject = new Guid("465614d0-0d52-4c11-bf6d-a05dec62876e");

		}
	}
}
