//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.SpecificationERP
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Спецификации"
	/// </summary>
	public partial class SpecificationERPTypes
	{
		
		internal SpecificationERPTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Спецификации"
		/// </summary>
		public SpecificationERPType SpecificationERPReferenceObject
		{
			get
			{
				return Find(Keys.SpecificationERPReferenceObject);
			}
		}
		
		protected override SpecificationERPType CreateClassObject(Guid classGuid)
		{
			return new SpecificationERPType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Спецификации"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Спецификации"
			/// </summary>
		   public static readonly Guid SpecificationERPReferenceObject = new Guid("44dbfda7-fb7d-44ea-908c-ad22a9b4916a");

		}
	}
}
