//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.GroupFinanceNomenclature
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Группы финансового учета номенклатуры"
	/// </summary>
	public partial class GroupFinanceNomenclatureReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Группы финансового учета номенклатуры"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("bf976229-6a1e-42fb-8662-102d665bce3c");
		
		/// <summary>
		/// Инициализирует новый экземпляр GroupFinanceNomenclatureReference для работы с объектами справочника "Группы финансового учета номенклатуры"
		/// </summary>
		public GroupFinanceNomenclatureReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, GroupFinanceNomenclatureReference.ReferenceId)
		{
		}
		
		private GroupFinanceNomenclatureReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Группы финансового учета номенклатуры"
		/// </summary>
		public new GroupFinanceNomenclatureTypes Classes
		{
			get
			{
				return ((GroupFinanceNomenclatureTypes)(base.Classes));
			}
		}
		
		protected override GroupFinanceNomenclatureReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			GroupFinanceNomenclatureType type = classObject as GroupFinanceNomenclatureType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsGroupFinanceNomenclatureReferenceObject)
			{
				return new GroupFinanceNomenclatureReferenceObject(this);
			}
			return new GroupFinanceNomenclatureReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<GroupFinanceNomenclatureReference, GroupFinanceNomenclatureTypes>
		{
			
			internal Factory()
			{
			}
			
			public override GroupFinanceNomenclatureReference CreateReference(ParameterGroup masterGroup)
			{
				return new GroupFinanceNomenclatureReference(masterGroup);
			}
			
			public override GroupFinanceNomenclatureTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new GroupFinanceNomenclatureTypes(masterGroup);
			}
		}
	}
}
