//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.GroupFinanceNomenclature
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.References.Links;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model.Parameters;
	
	
	/// <summary>
	/// Представляет объект справочника "Группы финансового учета номенклатуры"
	/// </summary>
	public partial class GroupFinanceNomenclatureReferenceObject
	{
		
		internal GroupFinanceNomenclatureReferenceObject(GroupFinanceNomenclatureReference reference) : 
				base(reference)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объекта
		/// </summary>
		public new GroupFinanceNomenclatureType Class
		{
			get
			{
				return ((GroupFinanceNomenclatureType)(base.Class));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Наименование"
		/// </summary>
		public StringParameter Name
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Name]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "GUID1C"
		/// </summary>
		public GuidParameter GUID1C
		{
			get
			{
				return ((GuidParameter)(this[FieldKeys.GUID1C]));
			}
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) параметров справочника "Группы финансового учета номенклатуры"
		/// </summary>
		public class FieldKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Наименование"
			/// </summary>
		   public static readonly Guid Name = new Guid("287b33df-debf-4821-b3b8-7138d26ded69");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "GUID1C"
			/// </summary>
		   public static readonly Guid GUID1C = new Guid("0f80340a-d517-4de8-9f38-93fabbad976d");

		}
	}
}
