//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.GroupFinanceNomenclature
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Группы финансового учета номенклатуры"
	/// </summary>
	public partial class GroupFinanceNomenclatureType
	{
		
		internal GroupFinanceNomenclatureType(GroupFinanceNomenclatureTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Группы финансового учета номенклатуры"
		/// </summary>
		public new GroupFinanceNomenclatureTypes Classes
		{
			get
			{
				return ((GroupFinanceNomenclatureTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Группа финансового учета номенклатуры" или порождён от него
		/// </summary>
		public bool IsGroupFinanceNomenclatureReferenceObject
		{
			get
			{
				return IsInherit(GroupFinanceNomenclatureTypes.Keys.GroupFinanceNomenclatureReferenceObject);
			}
		}
	}
}
