//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.GroupFinanceNomenclature
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Группы финансового учета номенклатуры"
	/// </summary>
	public partial class GroupFinanceNomenclatureTypes
	{
		
		internal GroupFinanceNomenclatureTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Группа финансового учета номенклатуры"
		/// </summary>
		public GroupFinanceNomenclatureType GroupFinanceNomenclatureReferenceObject
		{
			get
			{
				return Find(Keys.GroupFinanceNomenclatureReferenceObject);
			}
		}
		
		protected override GroupFinanceNomenclatureType CreateClassObject(Guid classGuid)
		{
			return new GroupFinanceNomenclatureType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Группы финансового учета номенклатуры"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Группа финансового учета номенклатуры"
			/// </summary>
		   public static readonly Guid GroupFinanceNomenclatureReferenceObject = new Guid("cf86a476-da6d-4f59-aab7-578e29c55bed");

		}
	}
}
