//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.StructNomenclature
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Предпросмотр структуры изделия"
	/// </summary>
	public partial class StructNomenclatureTypes
	{
		
		internal StructNomenclatureTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Предпросмотр структуры изделия"
		/// </summary>
		public StructNomenclatureType StructNomenclatureReferenceObject
		{
			get
			{
				return Find(Keys.StructNomenclatureReferenceObject);
			}
		}
		
		protected override StructNomenclatureType CreateClassObject(Guid classGuid)
		{
			return new StructNomenclatureType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Предпросмотр структуры изделия"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Предпросмотр структуры изделия"
			/// </summary>
		   public static readonly Guid StructNomenclatureReferenceObject = new Guid("6df4439f-b6d5-47a1-a31a-a0e8886f03f9");

		}
	}
}
