//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.StructNomenclature
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.References.Links;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model.Parameters;
	
	
	/// <summary>
	/// Представляет объект справочника "Предпросмотр структуры изделия"
	/// </summary>
	public partial class StructNomenclatureReferenceObject
	{
		
		internal StructNomenclatureReferenceObject(StructNomenclatureReference reference) : 
				base(reference)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объекта
		/// </summary>
		public new StructNomenclatureType Class
		{
			get
			{
				return ((StructNomenclatureType)(base.Class));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Наименование"
		/// </summary>
		public StringParameter Name
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Name]));
			}
		}
		
		/// <summary>
		/// Возвращает или задаёт связанный объект справочника "Номенклатура ERP" по связи "Номенклатура из ERP"
		/// </summary>
		public ReferenceObject NomenclatureERP
		{
			get
			{
				return GetObject(RelationKeys.NomenclatureERP);
			}
			set
			{
				SetLinkedObject(RelationKeys.NomenclatureERP, value);
			}
		}
		
		/// <summary>
		/// Возвращает или задаёт связанный объект справочника "Электронная структура изделий" по связи "Номенклатура в PDM"
		/// </summary>
		public ReferenceObject NomenclaturePDM
		{
			get
			{
				return GetObject(RelationKeys.NomenclaturePDM);
			}
			set
			{
				SetLinkedObject(RelationKeys.NomenclaturePDM, value);
			}
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) параметров справочника "Предпросмотр структуры изделия"
		/// </summary>
		public class FieldKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Наименование"
			/// </summary>
		   public static readonly Guid Name = new Guid("643cc639-a343-428a-9551-ba79718cf53b");

		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) связей и списков объектов справочника "Предпросмотр структуры изделия"
		/// </summary>
		public class RelationKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Номенклатура из ERP"
			/// </summary>
		   public static readonly Guid NomenclatureERP = new Guid("670ed240-7256-4aeb-8da8-1245f085d7c0");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Номенклатура в PDM"
			/// </summary>
		   public static readonly Guid NomenclaturePDM = new Guid("920e8b8b-2476-4b5b-a366-0a7476ac464a");

		}
	}
}
