//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.StructNomenclature
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Предпросмотр структуры изделия"
	/// </summary>
	public partial class StructNomenclatureType
	{
		
		internal StructNomenclatureType(StructNomenclatureTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Предпросмотр структуры изделия"
		/// </summary>
		public new StructNomenclatureTypes Classes
		{
			get
			{
				return ((StructNomenclatureTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Предпросмотр структуры изделия" или порождён от него
		/// </summary>
		public bool IsStructNomenclatureReferenceObject
		{
			get
			{
				return IsInherit(StructNomenclatureTypes.Keys.StructNomenclatureReferenceObject);
			}
		}
	}
}
