//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.StructNomenclature
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Предпросмотр структуры изделия"
	/// </summary>
	public partial class StructNomenclatureReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Предпросмотр структуры изделия"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("4d9934bc-285d-4b9c-8421-777cf2be3edb");
		
		/// <summary>
		/// Инициализирует новый экземпляр StructNomenclatureReference для работы с объектами справочника "Предпросмотр структуры изделия"
		/// </summary>
		public StructNomenclatureReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, StructNomenclatureReference.ReferenceId)
		{
		}
		
		private StructNomenclatureReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Предпросмотр структуры изделия"
		/// </summary>
		public new StructNomenclatureTypes Classes
		{
			get
			{
				return ((StructNomenclatureTypes)(base.Classes));
			}
		}
		
		protected override StructNomenclatureReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			StructNomenclatureType type = classObject as StructNomenclatureType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsStructNomenclatureReferenceObject)
			{
				return new StructNomenclatureReferenceObject(this);
			}
			return new StructNomenclatureReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<StructNomenclatureReference, StructNomenclatureTypes>
		{
			
			internal Factory()
			{
			}
			
			public override StructNomenclatureReference CreateReference(ParameterGroup masterGroup)
			{
				return new StructNomenclatureReference(masterGroup);
			}
			
			public override StructNomenclatureTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new StructNomenclatureTypes(masterGroup);
			}
		}
	}
}
