//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.GroupList
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Группы списка"
	/// </summary>
	public partial class GroupListTypes
	{
		
		internal GroupListTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Группа списка"
		/// </summary>
		public GroupListType GroupListReferenceObject
		{
			get
			{
				return Find(Keys.GroupListReferenceObject);
			}
		}
		
		protected override GroupListType CreateClassObject(Guid classGuid)
		{
			return new GroupListType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Группы списка"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Группа списка"
			/// </summary>
		   public static readonly Guid GroupListReferenceObject = new Guid("fb49453c-01ac-4176-b26b-9265f07bb7fe");

		}
	}
}
