//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.GroupList
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Группы списка"
	/// </summary>
	public partial class GroupListReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Группы списка"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("adedc26c-c007-47bd-a9b7-e23e09e6c033");
		
		/// <summary>
		/// Инициализирует новый экземпляр GroupListReference для работы с объектами справочника "Группы списка"
		/// </summary>
		public GroupListReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, GroupListReference.ReferenceId)
		{
		}
		
		private GroupListReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Группы списка"
		/// </summary>
		public new GroupListTypes Classes
		{
			get
			{
				return ((GroupListTypes)(base.Classes));
			}
		}
		
		protected override GroupListReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			GroupListType type = classObject as GroupListType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsGroupListReferenceObject)
			{
				return new GroupListReferenceObject(this);
			}
			return new GroupListReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<GroupListReference, GroupListTypes>
		{
			
			internal Factory()
			{
			}
			
			public override GroupListReference CreateReference(ParameterGroup masterGroup)
			{
				return new GroupListReference(masterGroup);
			}
			
			public override GroupListTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new GroupListTypes(masterGroup);
			}
		}
	}
}
