//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.GroupList
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Группы списка"
	/// </summary>
	public partial class GroupListType
	{
		
		internal GroupListType(GroupListTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Группы списка"
		/// </summary>
		public new GroupListTypes Classes
		{
			get
			{
				return ((GroupListTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Группа списка" или порождён от него
		/// </summary>
		public bool IsGroupListReferenceObject
		{
			get
			{
				return IsInherit(GroupListTypes.Keys.GroupListReferenceObject);
			}
		}
	}
}
