//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.EtalonProduct
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Эталонные изделия"
	/// </summary>
	public partial class EtalonProductReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Эталонные изделия"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("48188e26-6c77-4aa5-9edf-be718fe0ddd6");
		
		/// <summary>
		/// Инициализирует новый экземпляр EtalonProductReference для работы с объектами справочника "Эталонные изделия"
		/// </summary>
		public EtalonProductReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, EtalonProductReference.ReferenceId)
		{
		}
		
		private EtalonProductReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Эталонные изделия"
		/// </summary>
		public new EtalonProductTypes Classes
		{
			get
			{
				return ((EtalonProductTypes)(base.Classes));
			}
		}
		
		protected override EtalonProductReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			EtalonProductType type = classObject as EtalonProductType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsEtalonProductReferenceObject)
			{
				return new EtalonProductReferenceObject(this);
			}
			return new EtalonProductReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<EtalonProductReference, EtalonProductTypes>
		{
			
			internal Factory()
			{
			}
			
			public override EtalonProductReference CreateReference(ParameterGroup masterGroup)
			{
				return new EtalonProductReference(masterGroup);
			}
			
			public override EtalonProductTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new EtalonProductTypes(masterGroup);
			}
		}
	}
}
