//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.EtalonProduct
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Эталонные изделия"
	/// </summary>
	public partial class EtalonProductType
	{
		
		internal EtalonProductType(EtalonProductTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Эталонные изделия"
		/// </summary>
		public new EtalonProductTypes Classes
		{
			get
			{
				return ((EtalonProductTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Эталонные изделия" или порождён от него
		/// </summary>
		public bool IsEtalonProductReferenceObject
		{
			get
			{
				return IsInherit(EtalonProductTypes.Keys.EtalonProductReferenceObject);
			}
		}
	}
}
