//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.EtalonProduct
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Эталонные изделия"
	/// </summary>
	public partial class EtalonProductTypes
	{
		
		internal EtalonProductTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Эталонные изделия"
		/// </summary>
		public EtalonProductType EtalonProductReferenceObject
		{
			get
			{
				return Find(Keys.EtalonProductReferenceObject);
			}
		}
		
		protected override EtalonProductType CreateClassObject(Guid classGuid)
		{
			return new EtalonProductType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Эталонные изделия"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Эталонные изделия"
			/// </summary>
		   public static readonly Guid EtalonProductReferenceObject = new Guid("774fc226-2493-40aa-bbd5-9e828b282074");

		}
	}
}
