//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.Operation
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Операции ERP"
	/// </summary>
	public partial class OperationType
	{
		
		internal OperationType(OperationTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Операции ERP"
		/// </summary>
		public new OperationTypes Classes
		{
			get
			{
				return ((OperationTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Операции ERP" или порождён от него
		/// </summary>
		public bool IsDefaultOperationType
		{
			get
			{
				return IsInherit(OperationTypes.Keys.DefaultOperationType);
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Сборочная операция" или порождён от него
		/// </summary>
		public bool IsAssemblyOperationType
		{
			get
			{
				return IsInherit(OperationTypes.Keys.AssemblyOperationType);
			}
		}
	}
}
