//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.Operation
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Операции ERP"
	/// </summary>
	public partial class OperationTypes
	{
		
		internal OperationTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Операции ERP"
		/// </summary>
		public OperationType DefaultOperationType
		{
			get
			{
				return Find(Keys.DefaultOperationType);
			}
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Сборочная операция"
		/// </summary>
		public OperationType AssemblyOperationType
		{
			get
			{
				return Find(Keys.AssemblyOperationType);
			}
		}
		
		protected override OperationType CreateClassObject(Guid classGuid)
		{
			return new OperationType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Операции ERP"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Операции ERP"
			/// </summary>
		   public static readonly Guid DefaultOperationType = new Guid("e16d4c63-a8d1-48f7-8e0b-c98963174fda");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Сборочная операция"
			/// </summary>
		   public static readonly Guid AssemblyOperationType = new Guid("3983a6e5-63b6-4259-ab54-489da780cc27");

		}
	}
}
