//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.Operation
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.References.Links;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model.Parameters;
	
	
	/// <summary>
	/// Представляет объект справочника "Операции ERP"
	/// </summary>
	public partial class OperationReferenceObject
	{
		
		internal OperationReferenceObject(OperationReference reference) : 
				base(reference)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объекта
		/// </summary>
		public new OperationType Class
		{
			get
			{
				return ((OperationType)(base.Class));
			}
		}

		/// <summary>
		/// Возвращает параметр "Заход_UID"
		/// </summary>
		public StringParameter Zakhod_UID
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Zakhod_UID]));
			}
		}

		/// <summary>
		/// Возвращает параметр "Владелец"
		/// </summary>
		public StringParameter Vladelets
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Vladelets]));
			}
		}


		/// <summary>
		/// Возвращает параметр "Наименование"
		/// </summary>
		public StringParameter Name
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Name]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Код"
		/// </summary>
		public StringParameter Kod
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Kod]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "НомерОперации"
		/// </summary>
		public StringParameter NomerOperatsii
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.NomerOperatsii]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "ПорядковыйНомер"
		/// </summary>
		public StringParameter PoryadkovyyNomer
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.PoryadkovyyNomer]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "UID"
		/// </summary>
		public StringParameter UID
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.UID]));
			}
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) параметров справочника "Операции ERP"
		/// </summary>
		public class FieldKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Наименование"
			/// </summary>
		   public static readonly Guid Name = new Guid("8c425306-9ac0-48b2-80f3-8a5383225b3d");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Код"
			/// </summary>
		   public static readonly Guid Kod = new Guid("3135eddc-9813-49ad-945a-efc057f25f64");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "НомерОперации"
			/// </summary>
		   public static readonly Guid NomerOperatsii = new Guid("13f97943-e9c0-4243-ad96-4aa69d3ff0f3");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "ПорядковыйНомер"
			/// </summary>
		   public static readonly Guid PoryadkovyyNomer = new Guid("dd258a9f-a069-431b-8a9a-b7a5a531bc4d");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "UID"
			/// </summary>
		   public static readonly Guid UID = new Guid("ae659cfc-0ae9-4798-bd53-fbd4bb621f4e");
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Владелец"
			/// </summary>
			public static readonly Guid Vladelets = new Guid("832116a2-fc04-4bcb-9714-2023a0a6a1b3");
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Заход_UID"
			/// </summary>
			public static readonly Guid Zakhod_UID = new Guid("e1ed97bf-4b3b-4b65-ab46-4a8535b3b590");

		}
	}
}
