//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.Operation
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Операции ERP"
	/// </summary>
	public partial class OperationReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Операции ERP"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("0ec02cbc-d088-42d9-8fec-d9cf1da6d7e9");
		
		/// <summary>
		/// Инициализирует новый экземпляр OperationReference для работы с объектами справочника "Операции ERP"
		/// </summary>
		public OperationReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, OperationReference.ReferenceId)
		{
		}
		
		private OperationReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Операции ERP"
		/// </summary>
		public new OperationTypes Classes
		{
			get
			{
				return ((OperationTypes)(base.Classes));
			}
		}
		
		protected override OperationReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			OperationType type = classObject as OperationType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsDefaultOperationType)
			{
				return new OperationReferenceObject(this);
			}
			return new OperationReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<OperationReference, OperationTypes>
		{
			
			internal Factory()
			{
			}
			
			public override OperationReference CreateReference(ParameterGroup masterGroup)
			{
				return new OperationReference(masterGroup);
			}
			
			public override OperationTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new OperationTypes(masterGroup);
			}
		}
	}
}
