//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.EtalonWorkpiece
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Эталонные заготовки"
	/// </summary>
	public partial class EtalonWorkpieceReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Эталонные заготовки"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("812cd0ad-e8b8-44a5-a17e-d89530c1f7b3");
		
		/// <summary>
		/// Инициализирует новый экземпляр EtalonWorkpieceReference для работы с объектами справочника "Эталонные заготовки"
		/// </summary>
		public EtalonWorkpieceReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, EtalonWorkpieceReference.ReferenceId)
		{
		}
		
		private EtalonWorkpieceReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Эталонные заготовки"
		/// </summary>
		public new EtalonWorkpieceTypes Classes
		{
			get
			{
				return ((EtalonWorkpieceTypes)(base.Classes));
			}
		}
		
		protected override EtalonWorkpieceReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			EtalonWorkpieceType type = classObject as EtalonWorkpieceType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsEtalonWorkpieceReferenceObject)
			{
				return new EtalonWorkpieceReferenceObject(this);
			}
			return new EtalonWorkpieceReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<EtalonWorkpieceReference, EtalonWorkpieceTypes>
		{
			
			internal Factory()
			{
			}
			
			public override EtalonWorkpieceReference CreateReference(ParameterGroup masterGroup)
			{
				return new EtalonWorkpieceReference(masterGroup);
			}
			
			public override EtalonWorkpieceTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new EtalonWorkpieceTypes(masterGroup);
			}
		}
	}
}
