//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.EtalonWorkpiece
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Эталонные заготовки"
	/// </summary>
	public partial class EtalonWorkpieceType
	{
		
		internal EtalonWorkpieceType(EtalonWorkpieceTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Эталонные заготовки"
		/// </summary>
		public new EtalonWorkpieceTypes Classes
		{
			get
			{
				return ((EtalonWorkpieceTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Заготовки" или порождён от него
		/// </summary>
		public bool IsEtalonWorkpieceReferenceObject
		{
			get
			{
				return IsInherit(EtalonWorkpieceTypes.Keys.EtalonWorkpieceReferenceObject);
			}
		}
	}
}
