//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.EtalonWorkpiece
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Эталонные заготовки"
	/// </summary>
	public partial class EtalonWorkpieceTypes
	{
		
		internal EtalonWorkpieceTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Заготовки"
		/// </summary>
		public EtalonWorkpieceType EtalonWorkpieceReferenceObject
		{
			get
			{
				return Find(Keys.EtalonWorkpieceReferenceObject);
			}
		}
		
		protected override EtalonWorkpieceType CreateClassObject(Guid classGuid)
		{
			return new EtalonWorkpieceType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Эталонные заготовки"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Заготовки"
			/// </summary>
		   public static readonly Guid EtalonWorkpieceReferenceObject = new Guid("694c8b09-a246-4807-abdd-5544c58969e0");

		}
	}
}
