//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.Devision
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.References.Links;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model.Parameters;
	
	
	/// <summary>
	/// Представляет объект справочника "Подразделение"
	/// </summary>
	public partial class DevisionReferenceObject
	{
		
		internal DevisionReferenceObject(DevisionReference reference) : 
				base(reference)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объекта
		/// </summary>
		public new DevisionType Class
		{
			get
			{
				return ((DevisionType)(base.Class));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Наименование"
		/// </summary>
		public StringParameter Name
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Name]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Код"
		/// </summary>
		public StringParameter Kod
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Kod]));
			}
		}

        /// <summary>
        /// Возвращает параметр "Вид подразделения"
        /// </summary>
        public StringParameter VidPodrazdeleniya
        {
            get
            {
                return ((StringParameter)(this[FieldKeys.VidPodrazdeleniya]));
            }
        }

        /// <summary>
        /// Возвращает параметр "Тип подразделения"
        /// </summary>
        public StringParameter TipPodrazdeleniya
        {
            get
            {
                return ((StringParameter)(this[FieldKeys.TipPodrazdeleniya]));
            }
        }
        /// <summary>
        /// Возвращает параметр "Родитель"
        /// </summary>
        public StringParameter UID_Owner
        {
            get
            {
                return ((StringParameter)(this[FieldKeys.UID_Owner]));
            }
        }

        /// <summary>
        /// Возвращает параметр "НомерЦеха"
        /// </summary>
        public StringParameter NomerTsekha
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.NomerTsekha]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "UID"
		/// </summary>
		public StringParameter UID
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.UID]));
			}
		}

		public ReferenceObject GroupAndUsers
		{
			get
			{
				return GetObject(RelationKeys.GroupAndUsers);
			}
			set
			{
				SetLinkedObject(RelationKeys.GroupAndUsers, value);
			}
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) параметров справочника "Подразделение"
		/// </summary>
		public class FieldKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Наименование"
			/// </summary>
		   public static readonly Guid Name = new Guid("841b3ef9-8423-40b2-84af-08c0c56d0e5e");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Код"
			/// </summary>
		   public static readonly Guid Kod = new Guid("2eecae59-bf04-467a-8132-f73726625af0");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "НомерЦеха"
			/// </summary>
		   public static readonly Guid NomerTsekha = new Guid("4f4dca80-b42f-44ec-bc4c-e7aa191ff432");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "UID"
			/// </summary>
		   public static readonly Guid UID = new Guid("a5422a89-f536-404e-81ce-5dab3dcbedde");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) параметра "Вид подразделения"
            /// </summary>
            public static readonly Guid VidPodrazdeleniya = new Guid("79cbec3d-f7f9-4406-a7b9-46b2e0ed506c");

            /// <summary>
            /// Представляет уникальный идентификатор (GUID) параметра "Тип подразделения"
            /// </summary>
            public static readonly Guid TipPodrazdeleniya = new Guid("18c7fdd7-a898-4cd2-95ff-f63bf84cb928");
            /// <summary>
            /// Представляет уникальный идентификатор (GUID) параметра "Родитель"
            /// </summary>
            public static readonly Guid UID_Owner = new Guid("0dedc52b-5b6a-4db0-9dbe-1ec5e1eafb92");

        }

        public class RelationKeys
		{
            /// <summary>
            /// Представляет уникальный идентификатор (GUID) связи "Группы и пользователи"
            /// </summary>
            public static readonly Guid GroupAndUsers = new Guid("4e9be1c8-03e3-4885-b68f-fc7fe719316b");
		}

    }
}
