//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.Devision
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Подразделение"
	/// </summary>
	public partial class DevisionReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Подразделение"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("98ef9a6b-87b4-440c-a499-7d06fcab7a29");
		
		/// <summary>
		/// Инициализирует новый экземпляр DevisionReference для работы с объектами справочника "Подразделение"
		/// </summary>
		public DevisionReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, DevisionReference.ReferenceId)
		{
		}
		
		private DevisionReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Подразделение"
		/// </summary>
		public new DevisionTypes Classes
		{
			get
			{
				return ((DevisionTypes)(base.Classes));
			}
		}
		
		protected override DevisionReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			DevisionType type = classObject as DevisionType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsMainDevision)
			{
				return new DevisionReferenceObject(this);
			}
			return new DevisionReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<DevisionReference, DevisionTypes>
		{
			
			internal Factory()
			{
			}
			
			public override DevisionReference CreateReference(ParameterGroup masterGroup)
			{
				return new DevisionReference(masterGroup);
			}
			
			public override DevisionTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new DevisionTypes(masterGroup);
			}
		}
	}
}
