//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.FilterOtherProduct
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Прочие изделия НСИ"
	/// </summary>
	public partial class FilterOtherProductTypes
	{
		
		internal FilterOtherProductTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Прочие изделия НСИ"
		/// </summary>
		public FilterOtherProductType FilterOtherProductReferenceObject
		{
			get
			{
				return Find(Keys.FilterOtherProductReferenceObject);
			}
		}
		
		protected override FilterOtherProductType CreateClassObject(Guid classGuid)
		{
			return new FilterOtherProductType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Прочие изделия НСИ"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Прочие изделия НСИ"
			/// </summary>
		   public static readonly Guid FilterOtherProductReferenceObject = new Guid("e9ecf46c-8994-43a5-8ef1-216c704480f8");

		}
	}
}
