//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.FilterOtherProduct
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Прочие изделия НСИ"
	/// </summary>
	public partial class FilterOtherProductType
	{
		
		internal FilterOtherProductType(FilterOtherProductTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Прочие изделия НСИ"
		/// </summary>
		public new FilterOtherProductTypes Classes
		{
			get
			{
				return ((FilterOtherProductTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Прочие изделия НСИ" или порождён от него
		/// </summary>
		public bool IsFilterOtherProductReferenceObject
		{
			get
			{
				return IsInherit(FilterOtherProductTypes.Keys.FilterOtherProductReferenceObject);
			}
		}
	}
}
