//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.FilterOtherProduct
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Прочие изделия НСИ"
	/// </summary>
	public partial class FilterOtherProductReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Прочие изделия НСИ"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("7438eb83-5536-4de4-a64f-0601817ee26e");
		
		/// <summary>
		/// Инициализирует новый экземпляр FilterOtherProductReference для работы с объектами справочника "Прочие изделия НСИ"
		/// </summary>
		public FilterOtherProductReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, FilterOtherProductReference.ReferenceId)
		{
		}
		
		private FilterOtherProductReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Прочие изделия НСИ"
		/// </summary>
		public new FilterOtherProductTypes Classes
		{
			get
			{
				return ((FilterOtherProductTypes)(base.Classes));
			}
		}
		
		protected override FilterOtherProductReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			FilterOtherProductType type = classObject as FilterOtherProductType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsFilterOtherProductReferenceObject)
			{
				return new FilterOtherProductReferenceObject(this);
			}
			return new FilterOtherProductReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<FilterOtherProductReference, FilterOtherProductTypes>
		{
			
			internal Factory()
			{
			}
			
			public override FilterOtherProductReference CreateReference(ParameterGroup masterGroup)
			{
				return new FilterOtherProductReference(masterGroup);
			}
			
			public override FilterOtherProductTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new FilterOtherProductTypes(masterGroup);
			}
		}
	}
}
