//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.ReplacementERP
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Замены ERP"
	/// </summary>
	public partial class ReplacementERPType
	{
		
		internal ReplacementERPType(ReplacementERPTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Замены ERP"
		/// </summary>
		public new ReplacementERPTypes Classes
		{
			get
			{
				return ((ReplacementERPTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Замены ERP" или порождён от него
		/// </summary>
		public bool IsReplacementERPReferenceObject
		{
			get
			{
				return IsInherit(ReplacementERPTypes.Keys.ReplacementERPReferenceObject);
			}
		}
	}
}
