//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.ReplacementERP
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.References.Links;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model.Parameters;
	
	
	/// <summary>
	/// Представляет объект справочника "Замены ERP"
	/// </summary>
	public partial class ReplacementERPReferenceObject
	{
		
		internal ReplacementERPReferenceObject(ReplacementERPReference reference) : 
				base(reference)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объекта
		/// </summary>
		public new ReplacementERPType Class
		{
			get
			{
				return ((ReplacementERPType)(base.Class));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Наименование"
		/// </summary>
		public StringParameter Name
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Name]));
			}
		}
		
		/// <summary>
		/// Возвращает или задаёт связанный объект справочника "Номенклатура ERP" по связи "Заменяемый объект"
		/// </summary>
		public ReferenceObject Nomenclature
		{
			get
			{
				return GetObject(RelationKeys.Nomenclature);
			}
			set
			{
				SetLinkedObject(RelationKeys.Nomenclature, value);
			}
		}
		
		/// <summary>
		/// Возвращает или задаёт связанный объект справочника "Номенклатура ERP" по связи "Заменитель"
		/// </summary>
		public ReferenceObject Replacement
		{
			get
			{
				return GetObject(RelationKeys.Replacement);
			}
			set
			{
				SetLinkedObject(RelationKeys.Replacement, value);
			}
		}
		
		/// <summary>
		/// Возвращает связанные объекты справочника "Номенклатура ERP" по связи "Применяемость"
		/// </summary>
		public ReferenceObjectCollection Applicability
		{
			get
			{
				return Links.ToMany[RelationKeys.Applicability].Objects;
			}
		}
		
		/// <summary>
		/// Подключает объект справочника "Номенклатура ERP" по связи "Применяемость"
		/// </summary>
		/// <param name="newLinkedObject">
		/// Подключаемый объект
		/// </param>
		/// <returns>
		/// Подключённый объект
		/// </returns>
		public ReferenceObject AddApplicability(ReferenceObject newLinkedObject)
		{
			return AddLinkedObject(RelationKeys.Applicability, newLinkedObject);
		}
		
		/// <summary>
		/// Отключает объект справочника "Номенклатура ERP" по связи "Применяемость"
		/// </summary>
		/// <param name="linkedObject">
		/// Связанный объект
		/// </param>
		/// <returns>
		/// true, если объект был отключен
		/// </returns>
		public Boolean RemoveApplicability(ReferenceObject linkedObject)
		{
			return RemoveLinkedObject(RelationKeys.Applicability, linkedObject);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) параметров справочника "Замены ERP"
		/// </summary>
		public class FieldKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Наименование"
			/// </summary>
		   public static readonly Guid Name = new Guid("018bd776-c984-4e31-8e51-f0a3b7c46477");

		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) связей и списков объектов справочника "Замены ERP"
		/// </summary>
		public class RelationKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Заменяемый объект"
			/// </summary>
		   public static readonly Guid Nomenclature = new Guid("43bb2d60-0eb0-47a8-af72-a21fc00428b4");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Заменитель"
			/// </summary>
		   public static readonly Guid Replacement = new Guid("3024a058-982a-4f07-b218-b37fa45fe155");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Применяемость"
			/// </summary>
		   public static readonly Guid Applicability = new Guid("a70823da-1c5c-4cbc-bf9f-b7347e7b4f32");

		}
	}
}
