//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.VariantsMaterials
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.References.Links;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model.Parameters;
	
	
	/// <summary>
	/// Представляет объект справочника "Варианты материалов"
	/// </summary>
	public partial class VariantsMaterialsReferenceObject
	{
		
		internal VariantsMaterialsReferenceObject(VariantsMaterialsReference reference) : 
				base(reference)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объекта
		/// </summary>
		public new VariantsMaterialsType Class
		{
			get
			{
				return ((VariantsMaterialsType)(base.Class));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Наименование"
		/// </summary>
		public StringParameter Name
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Name]));
			}
		}
		
		/// <summary>
		/// Возвращает или задаёт связанный объект справочника "Материалы" по связи "Связанный материал"
		/// </summary>
		public ReferenceObject LinkedMaterial
		{
			get
			{
				return GetObject(RelationKeys.LinkedMaterial);
			}
			set
			{
				SetLinkedObject(RelationKeys.LinkedMaterial, value);
			}
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) параметров справочника "Варианты материалов"
		/// </summary>
		public class FieldKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Наименование"
			/// </summary>
		   public static readonly Guid Name = new Guid("b5262beb-f880-4316-b419-9dcbd89ba2b8");

		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) связей и списков объектов справочника "Варианты материалов"
		/// </summary>
		public class RelationKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Связанный материал"
			/// </summary>
		   public static readonly Guid LinkedMaterial = new Guid("4a110cc2-fb8f-453f-af45-9386ca0192c2");

		}
	}
}
