//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.VariantsMaterials
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Варианты материалов"
	/// </summary>
	public partial class VariantsMaterialsType
	{
		
		internal VariantsMaterialsType(VariantsMaterialsTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Варианты материалов"
		/// </summary>
		public new VariantsMaterialsTypes Classes
		{
			get
			{
				return ((VariantsMaterialsTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Варианты материалов" или порождён от него
		/// </summary>
		public bool IsVariantsMaterialsReferenceObject
		{
			get
			{
				return IsInherit(VariantsMaterialsTypes.Keys.VariantsMaterialsReferenceObject);
			}
		}
	}
}
