//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.VariantsMaterials
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Варианты материалов"
	/// </summary>
	public partial class VariantsMaterialsTypes
	{
		
		internal VariantsMaterialsTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Варианты материалов"
		/// </summary>
		public VariantsMaterialsType VariantsMaterialsReferenceObject
		{
			get
			{
				return Find(Keys.VariantsMaterialsReferenceObject);
			}
		}
		
		protected override VariantsMaterialsType CreateClassObject(Guid classGuid)
		{
			return new VariantsMaterialsType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Варианты материалов"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Варианты материалов"
			/// </summary>
		   public static readonly Guid VariantsMaterialsReferenceObject = new Guid("c31b1097-c789-4daf-9f3d-cbaba7af7b27");

		}
	}
}
