//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.FilterElectronicComponent
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.References.Links;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model.Parameters;
	
	
	/// <summary>
	/// Представляет объект справочника "Электронные компоненты НСИ"
	/// </summary>
	public partial class FilterElectronicComponentReferenceObject
	{
		
		internal FilterElectronicComponentReferenceObject(FilterElectronicComponentReference reference) : 
				base(reference)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объекта
		/// </summary>
		public new FilterElectronicComponentType Class
		{
			get
			{
				return ((FilterElectronicComponentType)(base.Class));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Наименование"
		/// </summary>
		//public StringParameter Name
		//{
		//	get
		//	{
		//		return ((StringParameter)(this[FieldKeys.Name]));
		//	}
		//}
		
		/// <summary>
		/// Возвращает параметр "Классификация"
		/// </summary>
		public StringParameter Classification
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Classification]));
			}
		}
		
		/// <summary>
		/// Возвращает или задаёт связанный объект справочника "Номенклатура ERP" по связи "Входящая номенклатура"
		/// </summary>
		public ReferenceObject InputNomenclature
		{
			get
			{
				return GetObject(RelationKeys.InputNomenclature);
			}
			set
			{
				SetLinkedObject(RelationKeys.InputNomenclature, value);
			}
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) параметров справочника "Электронные компоненты НСИ"
		/// </summary>
		public class FieldKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Наименование"
			/// </summary>
		   //public static readonly Guid Name = new Guid("f1b3a938-96ce-4b35-98b3-aa20c55381ee");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Классификация"
			/// </summary>
		   public static readonly Guid Classification = new Guid("c6631cb9-da36-4f06-ac00-38ef1598b19f");

		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) связей и списков объектов справочника "Электронные компоненты НСИ"
		/// </summary>
		public class RelationKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Входящая номенклатура"
			/// </summary>
		   public static readonly Guid InputNomenclature = new Guid("9ab44ecd-df1c-4821-bf41-7f08f2ea828f");

		}
	}
}
