//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.FilterElectronicComponent
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Электронные компоненты НСИ"
	/// </summary>
	public partial class FilterElectronicComponentTypes
	{
		
		internal FilterElectronicComponentTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Электронные компоненты НСИ"
		/// </summary>
		public FilterElectronicComponentType FilterElectronicComponentReferenceObject
		{
			get
			{
				return Find(Keys.FilterElectronicComponentReferenceObject);
			}
		}
		
		protected override FilterElectronicComponentType CreateClassObject(Guid classGuid)
		{
			return new FilterElectronicComponentType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Электронные компоненты НСИ"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Электронные компоненты НСИ"
			/// </summary>
		   public static readonly Guid FilterElectronicComponentReferenceObject = new Guid("c2c70d12-f92d-4cbc-a85c-f64f704dbf37");

		}
	}
}
