//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.FilterElectronicComponent
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Электронные компоненты НСИ"
	/// </summary>
	public partial class FilterElectronicComponentReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Электронные компоненты НСИ"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("7ba9cb82-2f3a-40df-b7c6-278c1aec8161");
		
		/// <summary>
		/// Инициализирует новый экземпляр FilterElectronicComponentReference для работы с объектами справочника "Электронные компоненты НСИ"
		/// </summary>
		public FilterElectronicComponentReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, FilterElectronicComponentReference.ReferenceId)
		{
		}
		
		private FilterElectronicComponentReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Электронные компоненты НСИ"
		/// </summary>
		public new FilterElectronicComponentTypes Classes
		{
			get
			{
				return ((FilterElectronicComponentTypes)(base.Classes));
			}
		}
		
		protected override FilterElectronicComponentReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			FilterElectronicComponentType type = classObject as FilterElectronicComponentType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsFilterElectronicComponentReferenceObject)
			{
				return new FilterElectronicComponentReferenceObject(this);
			}
			return new FilterElectronicComponentReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<FilterElectronicComponentReference, FilterElectronicComponentTypes>
		{
			
			internal Factory()
			{
			}
			
			public override FilterElectronicComponentReference CreateReference(ParameterGroup masterGroup)
			{
				return new FilterElectronicComponentReference(masterGroup);
			}
			
			public override FilterElectronicComponentTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new FilterElectronicComponentTypes(masterGroup);
			}
		}
	}
}
