//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.ConnectionNomenclatures
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Подключение номенклатур"
	/// </summary>
	public partial class ConnectionNomenclaturesTypes
	{
		
		internal ConnectionNomenclaturesTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Подключение номенклатур"
		/// </summary>
		public ConnectionNomenclaturesType ConnectionNomenclaturesReferenceObject
		{
			get
			{
				return Find(Keys.ConnectionNomenclaturesReferenceObject);
			}
		}
		
		protected override ConnectionNomenclaturesType CreateClassObject(Guid classGuid)
		{
			return new ConnectionNomenclaturesType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Подключение номенклатур"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Подключение номенклатур"
			/// </summary>
		   public static readonly Guid ConnectionNomenclaturesReferenceObject = new Guid("812dda8b-0d77-4e1a-a652-f3a02437b8be");

		}
	}
}
