//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.FilterUserManual
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.References.Links;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model.Parameters;
	
	
	/// <summary>
	/// Представляет объект справочника "Руководство по эксплуатации НСИ"
	/// </summary>
	public partial class FilterUserManualReferenceObject
	{
		
		internal FilterUserManualReferenceObject(FilterUserManualReference reference) : 
				base(reference)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объекта
		/// </summary>
		public new FilterUserManualType Class
		{
			get
			{
				return ((FilterUserManualType)(base.Class));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Объект"
		/// </summary>
		public StringParameter Name
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Name]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Классификация"
		/// </summary>
		public StringParameter Classification
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Classification]));
			}
		}
		
		/// <summary>
		/// Возвращает или задаёт связанный объект справочника "Номенклатура ERP" по связи "Номенклатура ERP"
		/// </summary>
		public ReferenceObject InputNomenclature
		{
			get
			{
				return GetObject(RelationKeys.InputNomenclature);
			}
			set
			{
				SetLinkedObject(RelationKeys.InputNomenclature, value);
			}
		}
		
		/// <summary>
		/// Возвращает связанные объекты справочника "Заявки на внесение эквивалентов" по связи "Заявка на эталон руководства по эксплуатации"
		/// </summary>
		public ReferenceObjectCollection RequestOnEtalon
		{
			get
			{
				return Links.ToMany[RelationKeys.RequestOnEtalon].Objects;
			}
		}
		
		/// <summary>
		/// Возвращает или задаёт связанный объект справочника "Заявки на внесение эквивалентов" по связи "Заявка на эквивалент НСИ (Эквивалент)"
		/// </summary>
		public ReferenceObject RequestOnEquivalent
		{
			get
			{
				return GetObject(RelationKeys.RequestOnEquivalent);
			}
			set
			{
				SetLinkedObject(RelationKeys.RequestOnEquivalent, value);
			}
		}
		
		/// <summary>
		/// Подключает объект справочника "Заявки на внесение эквивалентов" по связи "Заявка на эталон руководства по эксплуатации"
		/// </summary>
		/// <param name="newLinkedObject">
		/// Подключаемый объект
		/// </param>
		/// <returns>
		/// Подключённый объект
		/// </returns>
		public ReferenceObject AddRequestOnEtalon(ReferenceObject newLinkedObject)
		{
			return AddLinkedObject(RelationKeys.RequestOnEtalon, newLinkedObject);
		}
		
		/// <summary>
		/// Отключает объект справочника "Заявки на внесение эквивалентов" по связи "Заявка на эталон руководства по эксплуатации"
		/// </summary>
		/// <param name="linkedObject">
		/// Связанный объект
		/// </param>
		/// <returns>
		/// true, если объект был отключен
		/// </returns>
		public Boolean RemoveRequestOnEtalon(ReferenceObject linkedObject)
		{
			return RemoveLinkedObject(RelationKeys.RequestOnEtalon, linkedObject);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) параметров справочника "Руководство по эксплуатации НСИ"
		/// </summary>
		public class FieldKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Объект"
			/// </summary>
		   public static readonly Guid Name = new Guid("93beb3b4-a643-43f6-8ef5-6e3f3251f690");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Классификация"
			/// </summary>
		   public static readonly Guid Classification = new Guid("75f145bd-ef16-4cbc-8fd8-64b13af445bb");

		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) связей и списков объектов справочника "Руководство по эксплуатации НСИ"
		/// </summary>
		public class RelationKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Номенклатура ERP"
			/// </summary>
		   public static readonly Guid InputNomenclature = new Guid("516d921f-ca06-4330-a932-650e86561eb1");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Заявка на эталон руководства по эксплуатации"
			/// </summary>
		   public static readonly Guid RequestOnEtalon = new Guid("7978df13-a92e-4a95-99f8-1a1ca8afa9bf");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Заявка на эквивалент НСИ (Эквивалент)"
			/// </summary>
		   public static readonly Guid RequestOnEquivalent = new Guid("41b11c19-0c3d-4ce7-8960-5354af3ec20a");

		}
	}
}
