//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.FilterUserManual
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Руководство по эксплуатации НСИ"
	/// </summary>
	public partial class FilterUserManualTypes
	{
		
		internal FilterUserManualTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Руководство по эксплуатации НСИ"
		/// </summary>
		public FilterUserManualType FilterUserManual
		{
			get
			{
				return Find(Keys.FilterUserManual);
			}
		}
		
		protected override FilterUserManualType CreateClassObject(Guid classGuid)
		{
			return new FilterUserManualType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Руководство по эксплуатации НСИ"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Руководство по эксплуатации НСИ"
			/// </summary>
		   public static readonly Guid FilterUserManual = new Guid("c5d6d128-de65-41a5-bdb8-d43e8fedf028");

		}
	}
}
