//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.FilterUserManual
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Руководство по эксплуатации НСИ"
	/// </summary>
	public partial class FilterUserManualReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Руководство по эксплуатации НСИ"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("163a82d9-d909-46ee-9f84-4fd23b737f62");
		
		/// <summary>
		/// Инициализирует новый экземпляр FilterUserManualReference для работы с объектами справочника "Руководство по эксплуатации НСИ"
		/// </summary>
		public FilterUserManualReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, FilterUserManualReference.ReferenceId)
		{
		}
		
		private FilterUserManualReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Руководство по эксплуатации НСИ"
		/// </summary>
		public new FilterUserManualTypes Classes
		{
			get
			{
				return ((FilterUserManualTypes)(base.Classes));
			}
		}
		
		protected override FilterUserManualReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			FilterUserManualType type = classObject as FilterUserManualType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsFilterUserManual)
			{
				return new FilterUserManualReferenceObject(this);
			}
			return new FilterUserManualReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<FilterUserManualReference, FilterUserManualTypes>
		{
			
			internal Factory()
			{
			}
			
			public override FilterUserManualReference CreateReference(ParameterGroup masterGroup)
			{
				return new FilterUserManualReference(masterGroup);
			}
			
			public override FilterUserManualTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new FilterUserManualTypes(masterGroup);
			}
		}
	}
}
