//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.FilterStandartProduct
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Стандартные изделия НСИ"
	/// </summary>
	public partial class FilterStandartProductTypes
	{
		
		internal FilterStandartProductTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Стандартные изделия НСИ"
		/// </summary>
		public FilterStandartProductType FilterStandartProductReferenceObject
		{
			get
			{
				return Find(Keys.FilterStandartProductReferenceObject);
			}
		}
		
		protected override FilterStandartProductType CreateClassObject(Guid classGuid)
		{
			return new FilterStandartProductType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Стандартные изделия НСИ"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Стандартные изделия НСИ"
			/// </summary>
		   public static readonly Guid FilterStandartProductReferenceObject = new Guid("84482c39-0bc6-46f2-bf6f-d251e570908a");

		}
	}
}
