//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.FilterStandartProduct
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Стандартные изделия НСИ"
	/// </summary>
	public partial class FilterStandartProductReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Стандартные изделия НСИ"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("37cd9e9a-f167-4125-a8f2-d60fdde1f522");
		
		/// <summary>
		/// Инициализирует новый экземпляр FilterStandartProductReference для работы с объектами справочника "Стандартные изделия НСИ"
		/// </summary>
		public FilterStandartProductReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, FilterStandartProductReference.ReferenceId)
		{
		}
		
		private FilterStandartProductReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Стандартные изделия НСИ"
		/// </summary>
		public new FilterStandartProductTypes Classes
		{
			get
			{
				return ((FilterStandartProductTypes)(base.Classes));
			}
		}
		
		protected override FilterStandartProductReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			FilterStandartProductType type = classObject as FilterStandartProductType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsFilterStandartProductReferenceObject)
			{
				return new FilterStandartProductReferenceObject(this);
			}
			return new FilterStandartProductReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<FilterStandartProductReference, FilterStandartProductTypes>
		{
			
			internal Factory()
			{
			}
			
			public override FilterStandartProductReference CreateReference(ParameterGroup masterGroup)
			{
				return new FilterStandartProductReference(masterGroup);
			}
			
			public override FilterStandartProductTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new FilterStandartProductTypes(masterGroup);
			}
		}
	}
}
