//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.FilterStandartProduct
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.References.Links;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model.Parameters;
	
	
	/// <summary>
	/// Представляет объект справочника "Стандартные изделия НСИ"
	/// </summary>
	public partial class FilterStandartProductReferenceObject
	{
		
		internal FilterStandartProductReferenceObject(FilterStandartProductReference reference) : 
				base(reference)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объекта
		/// </summary>
		public new FilterStandartProductType Class
		{
			get
			{
				return ((FilterStandartProductType)(base.Class));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Наименование"
		/// </summary>
		//public StringParameter Name
		//{
		//	get
		//	{
		//		return ((StringParameter)(this[FieldKeys.Name]));
		//	}
		//}
		
		/// <summary>
		/// Возвращает параметр "Классификация"
		/// </summary>
		public StringParameter Classification
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Classification]));
			}
		}
		
		/// <summary>
		/// Возвращает или задаёт связанный объект справочника "Номенклатура ERP" по связи "Входящая номенклатура"
		/// </summary>
		public ReferenceObject InputNomenclature
		{
			get
			{
				return GetObject(RelationKeys.InputNomenclature);
			}
			set
			{
				SetLinkedObject(RelationKeys.InputNomenclature, value);
			}
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) параметров справочника "Стандартные изделия НСИ"
		/// </summary>
		public class FieldKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Наименование"
			/// </summary>
		   //public static readonly Guid Name = new Guid("9ae515c5-b4a2-4420-b823-74742f8940d6");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Классификация"
			/// </summary>
		   public static readonly Guid Classification = new Guid("e30b9bf8-9e2a-46d6-9dcd-6bed65a57205");

		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) связей и списков объектов справочника "Стандартные изделия НСИ"
		/// </summary>
		public class RelationKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Входящая номенклатура"
			/// </summary>
		   public static readonly Guid InputNomenclature = new Guid("159d42ca-fb94-43ed-b3ca-bf0558a679f1");

		}
	}
}
