//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.FilterStandartProduct
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Стандартные изделия НСИ"
	/// </summary>
	public partial class FilterStandartProductType
	{
		
		internal FilterStandartProductType(FilterStandartProductTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Стандартные изделия НСИ"
		/// </summary>
		public new FilterStandartProductTypes Classes
		{
			get
			{
				return ((FilterStandartProductTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Стандартные изделия НСИ" или порождён от него
		/// </summary>
		public bool IsFilterStandartProductReferenceObject
		{
			get
			{
				return IsInherit(FilterStandartProductTypes.Keys.FilterStandartProductReferenceObject);
			}
		}
	}
}
