//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.EtalonMaterial
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Эталонные материалы"
	/// </summary>
	public partial class EtalonMaterialType
	{
		
		internal EtalonMaterialType(EtalonMaterialTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Эталонные материалы"
		/// </summary>
		public new EtalonMaterialTypes Classes
		{
			get
			{
				return ((EtalonMaterialTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Эталонные материалы" или порождён от него
		/// </summary>
		public bool IsEtalonMaterialReferenceObject
		{
			get
			{
				return IsInherit(EtalonMaterialTypes.Keys.EtalonMaterialReferenceObject);
			}
		}
	}
}
