//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.EtalonMaterial
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Эталонные материалы"
	/// </summary>
	public partial class EtalonMaterialReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Эталонные материалы"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("29037f67-dd93-4444-8095-158262980f3c");
		
		/// <summary>
		/// Инициализирует новый экземпляр EtalonMaterialReference для работы с объектами справочника "Эталонные материалы"
		/// </summary>
		public EtalonMaterialReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, EtalonMaterialReference.ReferenceId)
		{
		}
		
		private EtalonMaterialReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Эталонные материалы"
		/// </summary>
		public new EtalonMaterialTypes Classes
		{
			get
			{
				return ((EtalonMaterialTypes)(base.Classes));
			}
		}
		
		protected override EtalonMaterialReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			EtalonMaterialType type = classObject as EtalonMaterialType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsEtalonMaterialReferenceObject)
			{
				return new EtalonMaterialReferenceObject(this);
			}
			return new EtalonMaterialReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<EtalonMaterialReference, EtalonMaterialTypes>
		{
			
			internal Factory()
			{
			}
			
			public override EtalonMaterialReference CreateReference(ParameterGroup masterGroup)
			{
				return new EtalonMaterialReference(masterGroup);
			}
			
			public override EtalonMaterialTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new EtalonMaterialTypes(masterGroup);
			}
		}
	}
}
