//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.EtalonMaterial
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Эталонные материалы"
	/// </summary>
	public partial class EtalonMaterialTypes
	{
		
		internal EtalonMaterialTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Эталонные материалы"
		/// </summary>
		public EtalonMaterialType EtalonMaterialReferenceObject
		{
			get
			{
				return Find(Keys.EtalonMaterialReferenceObject);
			}
		}
		
		protected override EtalonMaterialType CreateClassObject(Guid classGuid)
		{
			return new EtalonMaterialType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Эталонные материалы"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Эталонные материалы"
			/// </summary>
		   public static readonly Guid EtalonMaterialReferenceObject = new Guid("6632f4cb-43c7-4e6d-b97e-0fd7e53fa14f");

		}
	}
}
