//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.EtalonUserManual
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Эталоны руководства по эксплуатации"
	/// </summary>
	public partial class EtalonUserManualType
	{
		
		internal EtalonUserManualType(EtalonUserManualTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Эталоны руководства по эксплуатации"
		/// </summary>
		public new EtalonUserManualTypes Classes
		{
			get
			{
				return ((EtalonUserManualTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Эталоны руководства по эксплуатации" или порождён от него
		/// </summary>
		public bool IsEtalonUserManual
		{
			get
			{
				return IsInherit(EtalonUserManualTypes.Keys.EtalonUserManual);
			}
		}
	}
}
