//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.EtalonUserManual
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.References.Links;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model.Parameters;
	
	
	/// <summary>
	/// Представляет объект справочника "Эталоны руководства по эксплуатации"
	/// </summary>
	public partial class EtalonUserManualReferenceObject
	{
		
		internal EtalonUserManualReferenceObject(EtalonUserManualReference reference) : 
				base(reference)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объекта
		/// </summary>
		public new EtalonUserManualType Class
		{
			get
			{
				return ((EtalonUserManualType)(base.Class));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Наименование"
		/// </summary>
		public StringParameter Name
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Name]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Обозначение"
		/// </summary>
		public StringParameter Denotation
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Denotation]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Покупное"
		/// </summary>
		public BooleanParameter IsBuying
		{
			get
			{
				return ((BooleanParameter)(this[FieldKeys.IsBuying]));
			}
		}
		
		/// <summary>
		/// Возвращает или задаёт связанный объект справочника "Номенклатура ERP" по связи "Номенклатура ERP РПЭ"
		/// </summary>
		public ReferenceObject Nomenclature
		{
			get
			{
				return GetObject(RelationKeys.Nomenclature);
			}
			set
			{
				SetLinkedObject(RelationKeys.Nomenclature, value);
			}
		}
		
		/// <summary>
		/// Возвращает или задаёт связанный объект справочника "Справочник эквивалентных наименований" по связи "Эквиваленты РПЭ СЭН"
		/// </summary>
		public ReferenceObject Equivalent
		{
			get
			{
				return GetObject(RelationKeys.Equivalent);
			}
			set
			{
				SetLinkedObject(RelationKeys.Equivalent, value);
			}
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) параметров справочника "Эталоны руководства по эксплуатации"
		/// </summary>
		public class FieldKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Наименование"
			/// </summary>
		   public static readonly Guid Name = new Guid("4a4c13fb-4f0c-4e9e-8824-4cfc38ed34a9");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Обозначение"
			/// </summary>
		   public static readonly Guid Denotation = new Guid("3b9fba45-0759-47be-987f-a3553d3f9e87");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Покупное"
			/// </summary>
		   public static readonly Guid IsBuying = new Guid("5058f8a5-71d8-49dc-b075-bbad23aba3c5");

		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) связей и списков объектов справочника "Эталоны руководства по эксплуатации"
		/// </summary>
		public class RelationKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Номенклатура ERP РПЭ"
			/// </summary>
		   public static readonly Guid Nomenclature = new Guid("fda93048-e2db-4fed-94c1-794d5cc405ba");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Эквиваленты РПЭ СЭН"
			/// </summary>
		   public static readonly Guid Equivalent = new Guid("ce711c12-ac0b-4212-9dc3-80120d8f7fbc");

		}
	}
}
