//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.EtalonUserManual
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Эталоны руководства по эксплуатации"
	/// </summary>
	public partial class EtalonUserManualReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Эталоны руководства по эксплуатации"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("ac99952a-1662-485c-9e9c-8c8f58c2aa72");
		
		/// <summary>
		/// Инициализирует новый экземпляр EtalonUserManualReference для работы с объектами справочника "Эталоны руководства по эксплуатации"
		/// </summary>
		public EtalonUserManualReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, EtalonUserManualReference.ReferenceId)
		{
		}
		
		private EtalonUserManualReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Эталоны руководства по эксплуатации"
		/// </summary>
		public new EtalonUserManualTypes Classes
		{
			get
			{
				return ((EtalonUserManualTypes)(base.Classes));
			}
		}
		
		protected override EtalonUserManualReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			EtalonUserManualType type = classObject as EtalonUserManualType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsEtalonUserManual)
			{
				return new EtalonUserManualReferenceObject(this);
			}
			return new EtalonUserManualReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<EtalonUserManualReference, EtalonUserManualTypes>
		{
			
			internal Factory()
			{
			}
			
			public override EtalonUserManualReference CreateReference(ParameterGroup masterGroup)
			{
				return new EtalonUserManualReference(masterGroup);
			}
			
			public override EtalonUserManualTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new EtalonUserManualTypes(masterGroup);
			}
		}
	}
}
