//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.TypeNomenclatureERP
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Типы номенклатуры"
	/// </summary>
	public partial class TypeNomenclatureERPTypes
	{
		
		internal TypeNomenclatureERPTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Тип номенклатуры"
		/// </summary>
		public TypeNomenclatureERPType TypeNomenclatureERPReferenceObject
		{
			get
			{
				return Find(Keys.TypeNomenclatureERPReferenceObject);
			}
		}
		
		protected override TypeNomenclatureERPType CreateClassObject(Guid classGuid)
		{
			return new TypeNomenclatureERPType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Типы номенклатуры"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Тип номенклатуры"
			/// </summary>
		   public static readonly Guid TypeNomenclatureERPReferenceObject = new Guid("0a4ac5cd-38a8-476f-af9b-c4824d4d5c8c");

		}
	}
}
