//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.TypeNomenclatureERP
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Типы номенклатуры"
	/// </summary>
	public partial class TypeNomenclatureERPType
	{
		
		internal TypeNomenclatureERPType(TypeNomenclatureERPTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Типы номенклатуры"
		/// </summary>
		public new TypeNomenclatureERPTypes Classes
		{
			get
			{
				return ((TypeNomenclatureERPTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Тип номенклатуры" или порождён от него
		/// </summary>
		public bool IsTypeNomenclatureERPReferenceObject
		{
			get
			{
				return IsInherit(TypeNomenclatureERPTypes.Keys.TypeNomenclatureERPReferenceObject);
			}
		}
	}
}
