//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.Region
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Участки"
	/// </summary>
	public partial class RegionTypes
	{
		
		internal RegionTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Участки"
		/// </summary>
		public RegionType OwnerTypeRegion
		{
			get
			{
				return Find(Keys.OwnerTypeRegion);
			}
		}
		
		protected override RegionType CreateClassObject(Guid classGuid)
		{
			return new RegionType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Участки"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Участки"
			/// </summary>
		   public static readonly Guid OwnerTypeRegion = new Guid("d3ba4246-e998-4e13-9cce-bba7a87d078b");

		}
	}
}
