//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.Region
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Участки"
	/// </summary>
	public partial class RegionReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Участки"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("c17617b4-7c05-4880-ae24-913619dc0553");
		
		/// <summary>
		/// Инициализирует новый экземпляр RegionReference для работы с объектами справочника "Участки"
		/// </summary>
		public RegionReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, RegionReference.ReferenceId)
		{
		}
		
		private RegionReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Участки"
		/// </summary>
		public new RegionTypes Classes
		{
			get
			{
				return ((RegionTypes)(base.Classes));
			}
		}
		
		protected override RegionReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			RegionType type = classObject as RegionType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsOwnerTypeRegion)
			{
				return new RegionReferenceObject(this);
			}
			return new RegionReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<RegionReference, RegionTypes>
		{
			
			internal Factory()
			{
			}
			
			public override RegionReference CreateReference(ParameterGroup masterGroup)
			{
				return new RegionReference(masterGroup);
			}
			
			public override RegionTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new RegionTypes(masterGroup);
			}
		}
	}
}
