//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.Region
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.References.Links;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model.Parameters;
	
	
	/// <summary>
	/// Представляет объект справочника "Участки"
	/// </summary>
	public partial class RegionReferenceObject
	{
		
		internal RegionReferenceObject(RegionReference reference) : 
				base(reference)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объекта
		/// </summary>
		public new RegionType Class
		{
			get
			{
				return ((RegionType)(base.Class));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Наименование"
		/// </summary>
		public StringParameter Name
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Name]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Код"
		/// </summary>
		public StringParameter Kod
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Kod]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Владелец"
		/// </summary>
		public StringParameter Vladelets
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Vladelets]));
			}
		}

		/// <summary>
		/// Возвращает параметр "UID"
		/// </summary>
		public StringParameter UID
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.UID]));
			}
		}

		/// <summary>
		/// Возвращает или задаёт связанный объект справочника "Подразделение" по связи "Связь на владельца участка MDM"
		/// </summary>
		public ReferenceObject Link_Regions_Divisions
		{
			get
			{
				return GetObject(RelationKeys.Link_Regions_Divisions);
			}
			set
			{
				SetLinkedObject(RelationKeys.Link_Regions_Divisions, value);
			}
		}
		
		/// <summary>
		/// Возвращает или задаёт связанный объект справочника "Группы и пользователи" по связи "Группы и пользователи"
		/// </summary>
		public ReferenceObject Link_Region_Users
		{
			get
			{
				return GetObject(RelationKeys.Link_Region_Users);
			}
			set
			{
				SetLinkedObject(RelationKeys.Link_Region_Users, value);
			}
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) параметров справочника "Участки"
		/// </summary>
		public class FieldKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Наименование"
			/// </summary>
		   public static readonly Guid Name = new Guid("497f8611-0a3b-4b97-8693-9f54b8e827b3");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Код"
			/// </summary>
		   public static readonly Guid Kod = new Guid("1b4b52bf-eeb5-47b8-a353-87bc753ed636");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Владелец"
			/// </summary>
		   public static readonly Guid Vladelets = new Guid("ca1bbe9d-06f5-47eb-ab40-571f509ff803");
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Владелец"
			/// </summary>
			public static readonly Guid UID = new Guid("0a6e36ed-0cd5-4f95-8fbe-c8fe70a988d2");

		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) связей и списков объектов справочника "Участки"
		/// </summary>
		public class RelationKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Связь на владельца участка MDM"
			/// </summary>
		   public static readonly Guid Link_Regions_Divisions = new Guid("30d6407d-fcad-48e9-ac8c-fb4642978217");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Группы и пользователи"
			/// </summary>
		   public static readonly Guid Link_Region_Users = new Guid("f32e322e-4b2c-4e97-8e5c-764a6bbaca2b");

		}
	}
}
