//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.Region
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Участки"
	/// </summary>
	public partial class RegionType
	{
		
		internal RegionType(RegionTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Участки"
		/// </summary>
		public new RegionTypes Classes
		{
			get
			{
				return ((RegionTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Участки" или порождён от него
		/// </summary>
		public bool IsOwnerTypeRegion
		{
			get
			{
				return IsInherit(RegionTypes.Keys.OwnerTypeRegion);
			}
		}
	}
}
