//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.ConnectionNomenclatures
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Подключение номенклатур"
	/// </summary>
	public partial class ConnectionNomenclaturesReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Подключение номенклатур"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("e4bd403a-8892-4579-beab-0a884eadcfc3");
		
		/// <summary>
		/// Инициализирует новый экземпляр ConnectionNomenclaturesReference для работы с объектами справочника "Подключение номенклатур"
		/// </summary>
		public ConnectionNomenclaturesReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, ConnectionNomenclaturesReference.ReferenceId)
		{
            loadReference();
        }
		
		private ConnectionNomenclaturesReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
            loadReference();
        }
		
		/// <summary>
		/// Возвращает типы объектов справочника "Подключение номенклатур"
		/// </summary>
		public new ConnectionNomenclaturesTypes Classes
		{
			get
			{
				return ((ConnectionNomenclaturesTypes)(base.Classes));
			}
		}
		
		protected override ConnectionNomenclaturesReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			ConnectionNomenclaturesType type = classObject as ConnectionNomenclaturesType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsConnectionNomenclaturesReferenceObject)
			{
				return new ConnectionNomenclaturesReferenceObject(this);
			}
			return new ConnectionNomenclaturesReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<ConnectionNomenclaturesReference, ConnectionNomenclaturesTypes>
		{
			
			internal Factory()
			{
			}
			
			public override ConnectionNomenclaturesReference CreateReference(ParameterGroup masterGroup)
			{
				return new ConnectionNomenclaturesReference(masterGroup);
			}
			
			public override ConnectionNomenclaturesTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new ConnectionNomenclaturesTypes(masterGroup);
			}
		}
	}
}
