//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.ConnectionNomenclatures
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Подключение номенклатур"
	/// </summary>
	public partial class ConnectionNomenclaturesType
	{
		
		internal ConnectionNomenclaturesType(ConnectionNomenclaturesTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Подключение номенклатур"
		/// </summary>
		public new ConnectionNomenclaturesTypes Classes
		{
			get
			{
				return ((ConnectionNomenclaturesTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Подключение номенклатур" или порождён от него
		/// </summary>
		public bool IsConnectionNomenclaturesReferenceObject
		{
			get
			{
				return IsInherit(ConnectionNomenclaturesTypes.Keys.ConnectionNomenclaturesReferenceObject);
			}
		}

		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Подключение номенклатур ITRP" или порождён от него
		/// </summary>
		public bool ConnectionNomenclaturesReferenceObjectITRP
		{
			get
			{
				return IsInherit(ConnectionNomenclaturesTypes.Keys.ConnectionNomenclaturesReferenceObjectITRP);
			}
		}
	}
}
