//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.Profession
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Профессия"
	/// </summary>
	public partial class ProfessionTypes
	{
		
		internal ProfessionTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Профессия"
		/// </summary>
		public ProfessionType MainProfessionType
		{
			get
			{
				return Find(Keys.MainProfessionType);
			}
		}
		
		protected override ProfessionType CreateClassObject(Guid classGuid)
		{
			return new ProfessionType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Профессия"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Профессия"
			/// </summary>
		   public static readonly Guid MainProfessionType = new Guid("188db1eb-1913-468f-a14f-b5485c7e87af");

		}
	}
}
