//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.Profession
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.References.Links;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model.Parameters;
	
	
	/// <summary>
	/// Представляет объект справочника "Профессия"
	/// </summary>
	public partial class ProfessionReferenceObject
	{
		
		internal ProfessionReferenceObject(ProfessionReference reference) : 
				base(reference)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объекта
		/// </summary>
		public new ProfessionType Class
		{
			get
			{
				return ((ProfessionType)(base.Class));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Наименование"
		/// </summary>
		public StringParameter Name
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Name]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "UID"
		/// </summary>
		public StringParameter UID
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.UID]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Код"
		/// </summary>
		public StringParameter Kod
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Kod]));
			}
		}
		
		/// <summary>
		/// Возвращает или задаёт связанный объект справочника "Профессии" по связи "Профессии ТП"
		/// </summary>
		public ReferenceObject Link_3780_259
		{
			get
			{
				return GetObject(RelationKeys.ProfessionPDM);
			}
			set
			{
				SetLinkedObject(RelationKeys.ProfessionPDM, value);
			}
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) параметров справочника "Профессия"
		/// </summary>
		public class FieldKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Наименование"
			/// </summary>
		   public static readonly Guid Name = new Guid("ee5fee5a-390c-4009-add8-a0965ee7ce5f");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "UID"
			/// </summary>
		   public static readonly Guid UID = new Guid("69910676-1818-4795-a463-e6d6de214eaa");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Код"
			/// </summary>
		   public static readonly Guid Kod = new Guid("33b89da7-64eb-47d8-ac84-a764d87ae583");

		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) связей и списков объектов справочника "Профессия"
		/// </summary>
		public class RelationKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) связи "Профессии ТП"
			/// </summary>
		   public static readonly Guid ProfessionPDM = new Guid("1fe93298-7d24-4842-b885-3a70160ebe41");

		}
	}
}
