//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.Profession
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Профессия"
	/// </summary>
	public partial class ProfessionType
	{
		
		internal ProfessionType(ProfessionTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Профессия"
		/// </summary>
		public new ProfessionTypes Classes
		{
			get
			{
				return ((ProfessionTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Профессия" или порождён от него
		/// </summary>
		public bool IsMainProfessionType
		{
			get
			{
				return IsInherit(ProfessionTypes.Keys.MainProfessionType);
			}
		}
	}
}
