//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.Route
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Маршруты ERP"
	/// </summary>
	public partial class RouteTypes
	{
		
		internal RouteTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Маршруты ERP"
		/// </summary>
		public RouteType Route_Type
		{
			get
			{
				return Find(Keys.Route_Type);
			}
		}
		
		protected override RouteType CreateClassObject(Guid classGuid)
		{
			return new RouteType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Маршруты ERP"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Маршруты ERP"
			/// </summary>
		   public static readonly Guid Route_Type = new Guid("1c508e74-a9d7-4513-92fe-a6b6a44d1372");

		}
	}
}
