//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.Route
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.References.Links;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model.Parameters;
	
	
	/// <summary>
	/// Представляет объект справочника "Маршруты ERP"
	/// </summary>
	public partial class RouteReferenceObject
	{
		
		internal RouteReferenceObject(RouteReference reference) : 
				base(reference)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объекта
		/// </summary>
		public new RouteType Class
		{
			get
			{
				return ((RouteType)(base.Class));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Наименование"
		/// </summary>
		public StringParameter Name
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Name]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "UID"
		/// </summary>
		public StringParameter UID
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.UID]));
			}
		}

		public StringParameter Kod
		{
			
			get
			{
				if (Class.IsRouteType)
					return ((StringParameter)(this[FieldKeys.Kod]));
				return null;
			}
		}
		public StringParameter Vladelets
		{

			get
			{
				if (Class.IsRouteType)
					return ((StringParameter)(this[FieldKeys.Vladelets]));
				return null;
			}
		}
		public Int32Parameter NomerStroki
		{

			get
			{
				if (Class.IsRoutePointType)
					return ((Int32Parameter)(this[FieldKeys.NomerStroki]));
				return null;
			}
		}

		/// <summary>
		/// Уникальные идентификаторы (GUID) параметров справочника "Маршруты ERP"
		/// </summary>
		public class FieldKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Наименование"
			/// </summary>
		   public static readonly Guid Name = new Guid("9ab109a1-3e83-4475-afa3-890674bef1a4");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "UID"
			/// </summary>
		   public static readonly Guid UID = new Guid("ce6f666b-327b-4d6c-a185-5431695ce64c");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Код"
			/// </summary>
		   public static readonly Guid Kod = new Guid("0a6ea952-fe32-4b52-9f52-856010af842d");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Владелец"
			/// </summary>
		   public static readonly Guid Vladelets = new Guid("cc758815-8a75-4f5a-b40f-d03aa63c9bd4");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "НомерСтроки"
			/// </summary>
		   public static readonly Guid NomerStroki = new Guid("e34612c6-2359-4900-b1c0-53fe8324a560");

		}
	}
}
