//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.Route
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Маршруты ERP"
	/// </summary>
	public partial class RouteReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Маршруты ERP"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("8f13c934-bd8a-44a4-8110-690aa7267c91");
		
		/// <summary>
		/// Инициализирует новый экземпляр RouteReference для работы с объектами справочника "Маршруты ERP"
		/// </summary>
		public RouteReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, RouteReference.ReferenceId)
		{
		}
		
		private RouteReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Маршруты ERP"
		/// </summary>
		public new RouteTypes Classes
		{
			get
			{
				return ((RouteTypes)(base.Classes));
			}
		}
		
		protected override RouteReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			RouteType type = classObject as RouteType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsMainTypeRoute)
			{
				return new RouteReferenceObject(this);
			}
			return new RouteReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<RouteReference, RouteTypes>
		{
			
			internal Factory()
			{
			}
			
			public override RouteReference CreateReference(ParameterGroup masterGroup)
			{
				return new RouteReference(masterGroup);
			}
			
			public override RouteTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new RouteTypes(masterGroup);
			}
		}
	}
}
