//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.Route
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Маршруты ERP"
	/// </summary>
	public partial class RouteTypes
	{
		
		internal RouteTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Маршруты ERP"
		/// </summary>
		public RouteType MainTypeRoute
		{
			get
			{
				return Find(Keys.MainTypeRoute);
			}
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Маршрут"
		/// </summary>
		public RouteType RouteType
		{
			get
			{
				return Find(Keys.RouteType);
			}
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Цехопереход"
		/// </summary>
		public RouteType RoutePointType
		{
			get
			{
				return Find(Keys.RoutePointType);
			}
		}
		
		protected override RouteType CreateClassObject(Guid classGuid)
		{
			return new RouteType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Маршруты ERP"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Маршруты ERP"
			/// </summary>
		   public static readonly Guid MainTypeRoute = new Guid("6228b4cb-5a75-491c-8661-da8b0bc0ac69");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Маршрут"
			/// </summary>
		   public static readonly Guid RouteType = new Guid("921dd95e-90fa-427b-92a6-1b0248d9b978");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Цехопереход"
			/// </summary>
		   public static readonly Guid RoutePointType = new Guid("83625249-d8ab-407e-9c9c-0724f935178c");

		}
	}
}
